import {FormattedMessage} from "react-intl";
import React from "react";
import { Breadcrumb, Button, Checkbox, Radio } from 'antd';

/**
 * 多语言英文
 */
export default {
  
  'Public.ChooseLocation':'Choose your language',
  'Public.Export':'Export',
  'Public.Cancel':'Cancel',
  'Public.Batch Export':'Batch Export',
  'Public.Reminder100records':'Reminder: up to 100 records',
  "Public.GetDataFailed": 'Get Data Failed',
  '分割线Public': '-----------------Public----------------------',
  'Order.whetherToSplitOrder':'Whether to split order',
  'Order.COD':'COD',
  'Order.deliveryAfterPayment':'Delivery after payment',
  'Order.capturePaymentWhen':'Capture payment when',
  'Order.none':'None',
  'Order.cashOnDelivery':'Cash on delivery',
  'Order.fieldRuleSetting':'Field rule setting',
  'Order.AdvanceSearch':'Advance Search',
  'Order.recommenderId':'Recommender id',
  'Order.recommenderName':'Recommender name',
  'Order.clinicName':'Auditor name',
  'Order.clinicID':'Auditor id',
  'Order.OrderType':'Order type',
  'Order.OrderSource':'Order source',
  'Order.orderNumber':'Order number',
  'Order.subscriptionNumber':'Subscription number',
  'Order.productFirstLetterUpperCase':'Product',
  'Order.items':'Items',
  'Order.needsToBeOperated':'Please select the order that needs to be operated',
  'Order.ConfirmThatAllProducts':'Confirm that all products have been received?',
  'Order.than100Characters':'Please input less than 100 characters',
  'Order.OnceRejected':'Once rejected, we will return the payment for this order to the consumer',
  'Order.Subscription':'Subscription',
  'Order.piece':'piece',
  'Order.theOrderHasBeenApproved':'Do you confirm that the order has been approved?',
  'Order.PleaseSelectMember':'Please select member',
  'Order.ProductsHaveBeenReceived':'Confirm that all products have been received?',
  'Order.more':'more',
  'Order.orderAttachment':'Order attachment',
  'Order.typePictures':'Only jpg, png, gif type pictures can be uploaded',
  'Order.ImageSize':'Image size cannot exceed 5MB!',
  'Order.uploadFailed':'upload failed',
  'Order.productList':'Product list',
  'Order.product':'Product',
  'Order.refundableAmount':'Refundable amount',
  'Order.refundTime':'Refund time',
  'Order.pointsRefundable':'Points refundable',
  'Order.chargebackStatus':'Chargeback status',
  'Order.actualRefundAmount':'Actual refund amount',
  'Order.actualRefundPoints':'Actual refund points',
  'Order.yes':'yes',
  'Order.SubscriptionNumber':'Subscription number',
  'Order.ReturnOrderNumber':'Return order number',
  'Order.no':'no',
  'Order.SubscriptionType': 'Subscription type1',
  'Order.SubscriptionOrderTime': 'Subscription order time',
  'Order.SubscriptionPlanType': 'Subscription plan type',
  'Order.PromotionCode': 'Promotion code',
  'Order.CouponCode': 'Coupon code',
  'Order.Created': 'Created',
  'Order.PendingReview': 'Pending review',
  'Order.ToBeDelivered': 'To be delivered',
  'Order.PartiallyShipped': 'Partially Shipped',
  'Order.PartiallyDelivered': 'Partially Delivered',
  'Order.Delivered': 'Delivered',
  'Order.Cancelled': 'Cancelled',
  'Order.Rejected': 'Rejected',
  'Order.DeleteSuccessfully': 'Delete successfully',
  'Order.DeleteFailed': 'Delete Failed',
  'Order.AddFailed': 'Add Failed',
  'Order.UpdateFailed': 'Update Failed',
  'Order.PleaseInputComment': 'Please input comment',
  'Order.deleteThisComment': 'Are you sure you want to delete this comment?',
  'Order.LogisticMandotory': 'Logistic info is mandotory',
  'Order.LogisticsCompany': 'Logistics company',
  'Order.Yes': 'Yes',
  'Order.No': 'No',
  'Order.inputLogisticsCompany': 'Please input logistics company',
  'Order.notLogisticsCompany': 'You have not set up a common logistics company',
  'Order.LogisticsOrder': 'Logistics order',
  'Order.inputLogisticsOrder': 'Please input logistics order',
  'Order.DeliverDate': 'Deliver Date',
  'Order.inputDeliverDate': 'Please input deliver date',
  'Order.operationLog': 'Operation log',
  'Order.LogisticsSingleNumber': 'Logistics single number',
  'Order.DeliverGoods': 'Deliver goods',
  'Order.Prompt': 'Prompt',
  'Order.WhetherToInvalidate': 'Whether to invalidate this delivery record',
  'Order.100Characters': 'Please input less than 100 characters',
  'Order.ConfirmReceiptAll': 'Confirm receipt of all items?',
  'Order.enterTheReason': 'Please enter the reason for rejection',
  'Order.Enter100Characters': 'Enter up to 100 characters',
  'Order.SKUCode':'SKU Code',
  'Order.PetCategory': 'Pet category',
  'Order.PetName': 'Pet name',
  'Order.PetDetails': 'Pet details',
  'Order.ExternalOrderId': 'External order id',
  'Order.productAmount': 'Product amount',
  'Order.AutoshipDiscount': 'Autoship Discount',
  'Order.CreateBy': 'Create by',
  'Order.tax': 'tax',
  'Order.PetOwnerName': 'Pet owner name',
  'Order.PetOwnerType': 'Pet owner type',
  'Order.PetOwnerAccount': 'Pet owner account',
  'Order.DeliveryAddress': 'Delivery Address',
  'Order.FirstName': 'First name',
  'Order.Partner': 'Partner',
  'Order.AuditorName': 'Auditor name',
  'Order.AuditorId': 'Auditor id',
  'Order.RecommenderId': 'Recommender id',
  'Order.RecommenderName': 'Recommender name',
  'Order.Address': 'Address',
  'Order.Country': 'Country',
  'Order.City': 'City',
  'Order.PostalCode': 'Postal code',
  'Order.PhoneNumber': 'Phone number',
  'Order.State': 'State',
  'Order.BillingAddress': 'Billing Address',
  'Order.Pet': 'Pet',
  'Order.Gender': 'Gender',
  'Order.Birthday': 'Birthday',
  'Order.Breed': 'Breed',
  'Order.Sensitivities': 'Sensitivities',
  'Order.Lifestyle': 'Lifestyle',
  'Order.Activity': 'Activity',
  'Order.Sterilized': 'Sterilized',
  'Order.Ship': 'Ship',
  'Order.ReReview': 'Re-review',
  'Order.Confirmreceipt': 'Confirm receipt',
  'Order.ConfirmTo': 'Confirm to return the selected order for re approval ?',
  'Order.ConfirmReceiptOf': 'Confirm receipt of all items?',
  'Order.amountReceivable': 'Amount receivable',
  'Order.Operation': 'Operation',
  'Order.paymentId': 'Payment Id',
  'Order.paymentTime': 'Payment Time',
  'Order.name': 'Name',
  'Order.email': 'Email',
  'Order.confirm': 'Confirm',
  'Order.cardNumber': 'Card number',
  'Order.orderDetails': 'Order Details',
  'Order.OrderList': 'Order list',
  'Order.deliveryRecord': 'Delivery Record',
  'Order.collectionRecords': 'Payment Records',
  'Order.back': 'Back',
  'Order.SKU Code': 'SKU Code',
  'Order.Product Name': 'Product Name',
  'Order.promotionAmount': 'Promotion amount',
  'Order.Reject': 'Reject',
  'Order.ConfirmToReturn': 'Confirm to return the selected order for re approval ?',
  'Order.hasBeenApproved': 'Do you confirm that the order has been approved?',
  'Order.allProductsHave': 'Confirm that all products have been received?',
  'Order.SeeDetails': 'See details',
  'Order.SinglePurchase': 'Single purchase',
  'Order.1stAutoshipOrder': '1st autoship order',
  'Order.RecurrentOrders': 'Recurrent orders of autoship',
  'Order.advanceSearch':'Advance Search',
  'Order.subscription':'Subscription',
  'Order.first':'First',
  'Order.recurrent':'Recurrent',
  'Order.contractProduct':'Contract product',
  'Order.club':'Club',
  'Order.autoship':'Autoship',
  'Order.fgs':'FGS',
  'Order.felin':`L'Atelier Feline`,
  'Order.subscriptionType':'Subscription type',
  'Order.subscriptionOrderTime':'Subscription order time',
  'Order.subscriptionPlanType':'Subscription plan type',
  'Order.orderType':'Order type',
  'Order.promotionCode':'Promotion code',
  'Order.couponCode':'Coupon code',
  'Order.cat':'Cat',
  'Order.dog':'Dog',
  'Order.smartFeeder':'SmartFeeder',
  'Order.created':'Created',
  'Order.partiallyShipped':'Partially Shipped',
  'Order.partiallyDelivered':'Partially Delivered',
  'Order.delivered':'Delivered',
  'Order.cancelled':'Cancelled',
  'Order.authorized':'Authorized',
  'Order.createBy':'Create by',
  'Order.petCategory':'Pet category',
  'Order.petName':'Pet name',
  'Order.petDetails':'Pet details',
  'Order.externalOrderId':'External order id',
  'Order.petOwnerType':'Pet owner type',
  'Order.partner':'Partner',
  'Order.autoshipDiscount':'Autoship Discount',
  'Order.deliveryAddress':'Delivery Address',
  'Order.firstName':'First name',
  'Order.address1':'Address 1',
  'Order.address2':'Address 2',
  'Order.country':'Country',
  'Order.city':'City',
  'Order.estimatedDeliveryDate':'Estimated delivery date',
  'Order.estimatedDeliveryDateDesc':'Delivery time from {minDay} to {maxDay} working days',
  'Order.estimatedDeliveryDateDescEqual':'Delivery time {day} working days',
  'Order.state':'State',
  'Order.billingAddress':'Billing Address',
  'Order.pet':'Pet',
  'Order.gender':'Gender',
  'Order.birthday':'Birthday',
  'Order.breed':'Breed',
  'Order.sensitivities':'Sensitivities',
  'Order.lifestyle':'Lifestyle',
  'Order.activity':'Activity',
  'Order.sterilized':'Sterilized',
  'Order.logisticsCompany':'Logistics company',
  'Order.logisticsSingleNumber':'Logistics single number',
  'Order.prompt':'Prompt',
  'Order.Approve':'Approve',
  'Order.RecipientAccepted':'Recipient accepted',
  'Order.RecipientRejected':'Recipient rejected',
  'Order.RealRefund':'Real refund',
  'Order.Return':'Return',
  'Order.applicationTime': 'Application time',
  'Order.payWay': 'Payment method',
  'Order.consumer': 'Consumer',
  'Order.consumerLevel': 'Pet owner type',
  'Order.Logistics information to be filled in': 'Logistics information to be filled in',
  'Order.Pending refund': 'Pending refund',
  'Order.Finished': 'Finished',
  'Order.PleaseFillOutThe': 'Please fill out the',
  'Order.reason': 'reason',
  'Order.POS':'POS',
  'Order.OK':'OK',
  'Order.offline.noCustomerAlert':'Please fill consumer information!',
  'Order.offline.orderNotSuccess':'Order not successful',
  'Order.offline.retryAlert':'You can switch payment type or try it again!',
  'Order.offline.felin':"L'Atelier Feline",
  'Order.offline.directCheckout':'Direct check-out',
  'Order.offline.recommendation':'Recommendation',
  'Order.offline.shoppingCart':'Shopping cart',
  'Order.offline.totalPrice':'Total price',
  'Order.offline.noOfProducts':'No. of products',
  'Order.offline.totalWeight':'Total weight',
  'Order.offline.cleanUp':'Clean up',
  'Order.offline.checkout':'Checkout',
  'Order.offline.consumerInformation':'Consumer information',
  'Order.offline.consumerName':'Consumer name',
  'Order.offline.consumerNameRequired':'Consumer name is required',
  'Order.offline.consumerPhone':'Consumer phone',
  'Order.offline.consumerEmail':'Consumer email',
  'Order.offline.consumerEmailRequired':'Please fill in correct email',
  'Order.offline.offlineStore':'Offline store',
  'Order.offline.Guest':'Guest',
  'Order.offline.Member':'Member',
  'Order.offline.petOwnerType':'Pet owner type',
  'Order.offline.paymentType':'Payment type',
  'Order.offline.cash':'Cash',
  'Order.offline.creditCard':'Credit card',
  'Order.offline.productOverview':'Product overview',
  'Order.offline.success':'Successfully',
  'Order.offline.refillAlert':'Do you want to refill your order?',
  'Order.offline.yes':'Yes',
  'Order.offline.no':'No',
  'Order.offline.complete':'Complete',
  'Order.offline.recommendationId':'Recommendation ID',
  'Order.offline.appointmentTime':'Appointment time',
  'Order.offline.recommendationProducts':'Recommended products',
  'Order.offline.booked':'Booked',
  'Order.offline.arrived':'Arrived',
  'Order.offline.canceled':'Canceled',
  'Order.offline.queryStateTitle':'Check payment status',
  'Order.offline.queryStateContent':'Your can check payment status after customer authorization!',
  'Order.delivery.Order':'Order',
  'Order.Step1':'Step1',
  'Order.Step2':'Step2',
  'Order.Step3':'Step3',
  'Order.Consumer information':'Consumer information',
  'Order.Selected product':'Selected product',
  'Order.Delivery & payment information':'Delivery & payment information',
  'Order.Register':'Register',
  'Order.Product list':'Product list',
  'Order.Pet owner list':'Pet owner list',
  'Order.Next step':'Next step',
  'Order.piypoa':'Please input your Pet owner account!',
  'Order.Image':'Image',
  'Order.SKU':'SKU',
  'Order.Product name':'Product name',
  'Order.Stock availability':'Stock availability',
  'Order.Marketing price':'Marketing price',
  'Order.Subscription price':'Subscription price',
  'Order.Selected Subscription':'Selected Subscription',
  'Order.Frequency':'Frequency',
  'Order.Total amount':'Total amount',
  'Order.Product amount':'Product amount',
  'Order.deleteproduct':'Are you sure you want to delete this product?',
  'Order.add':'add',
  'Order.Choose product':'Choose product',
  'Order.Product category':'Product category',
  'Order.View all':'View all',
  'Order.checkout':'Please process to checkout in the new window.',
  'Order.open':'If the new window fails to open, click',
  'Order.here':'here',
  'Order.failure':'The order is placed failure for',
  'Order.successfully':'The order is placed successfully for',
  'Order.returnDescription':'Return description',
  'Order.returnOrderAttachment':'Return order attachment',
  'Order.returnReason': 'Return reason',
  'Order.logisticsInformation':'Logistics information',
  'Order.returnOrderStatus':'Return order status',
  'Order.remark':'Remark',
  'Order.reviewRejected': 'Review rejected', 
  'Order.receiedRejected': 'Receied rejected', 
  'Order.refundRejected': 'Refund rejected',
  'Order.Selectreturnproducts': 'Order.Select return products',
  'Order.Specification': 'Specification',
  'Order.Returnunitprice': 'Return unit price',
  'Order.Returnquantity': 'Return quantity',
  'Order.Pleaseenterreturnquantity': 'Please enter return quantity',
  'Order.Returnquantityshould': 'Return quantity should be in round numbers only',
  'Order.Theamountreturnedmustnotexceed': 'The amount returned must not exceed the amount refundable',
  'Order.Returnablenumber': 'Returnable number',
  'Order.Subtotalofreturnamount': 'Subtotal of return amount',
  'Order.RetractableIntegral': 'Retractable integral',
  'Order.Returnreason': 'Return reason',
  'Order.Pleaseselectchargebackreason': 'Please select chargeback reason',
  'Order.Returnmethod': 'Return method',
  'Order.Pleaseselectreturnmethod': 'Please select return method',
  'Order.Returndescription': 'Return description',
  'Order.Returndescriptioncannotbeblank': 'Return description cannot be blank !',
  'Order.Attachmentinformation': 'Attachment information',
  'Order.PleaseaddyourreturOrder.savencredentialsTip': 'Please add your return credentials to the attachment. Supported picture formats: JPG, JPEG, PNG, GIF, file size no more than 5M, and upload a maximum of 10',
  'Order.Refundableamountcannotbeblank': 'Refundable amount cannot be blank !',
  'Order.Refundableamount': 'Refundable amount',
  'Order.Uploaderror': 'Upload error',
  'Order.Filesizecannotexceed 5M' : 'File size cannot exceed 5M',
  'Order.Fileformaterror': 'File format error',
  'Order.NoData': 'No Data',
  'Order.cancel': 'Cancel',
  'Order.Addreturnorder': 'Add return order',
  'Order.Thereisnoreasonforthereturn': 'There is no reason for the return', 
  'Order.skipLogistics':'Skip logistics',
  'Order.skipLogisticsAlert':'Are you sure skip logistics?',
  'Order.fillLogistics':'Fill in logistics',
  'Order.detail':'Detail',
  'Order.confirmRefund':'Confirm Refund',
  'Order.refundAlert1':'Do you confirm the refund?',
  'Order.refundAlert2':'What is the amount of the refund?',
  'Order.approveAlert':'Is the audit approved?',
  'Order.receiptAlert':'Do you confirm receipt of the goods?',
  'Order.reasonIsEmpty':'reason is empty!',
  'Order.oneToOneHun':'1 to 100 words',
  'Order.pleaseInputReason':'Please input the reason for',
  

  '分割线Order': '--------------------Order-------------------',


  'Subscription.consumerName':'Consumer name',
  'Subscription.operation':'Operation',
  'Subscription.SubscriptionStatus':'Subscription status',
  'Subscription.noData':'no data',
  'Subscription.subscriptionDate':'Subscription date',
  'Subscription.SaveFeedbackSuccessfully':'Save feedback successfully',
  'Subscription.AfterWelcomePackReceived':'After 1st delivery',
  'Subscription.RateDelivery':'Rate delivery',
  'Subscription.scaleFrom':'scale from 1 to 5',
  'Subscription.RateThePack':'Rate the pack',
  'Subscription.Comments':'Comments',
  'Subscription.deliveryConfirmation':'After 4th delivery',
  'Subscription.NPS':'NPS',
  'Subscription.scaleFrom10':'scale from 1 to 10',
  'Subscription.DeliveryScheduleFit':'Delivery schedule fit',
  'Subscription.ReasonOfInterest':'Reason of interest of the Club',
  'Subscription.After3rdDelivery':'1 year subscription',
  'Subscription.ConsultationQuality':'Rate PA consultation quality',
  'Subscription.UnnecessaryServices':'Unnecessary services',
  'Subscription.NecessaryServices':'Necessary services',
  'Subscription.Feedback':'Subscription program cancellation',
  'Subscription.ReasonForCancellation':'Reason for cancellation of membership',
  'Subscription.SuggestionsForImprovement':'Suggestions for improvement',
  'Subscription.FeedbackForClinics':'Feedback for clinics',
  'Subscription.Visit':'Visit',
  'Subscription.QualityOfService':'Quality of service',
  'Subscription.VeterinarianQualification':'Veterinarian qualification',
  'Subscription.Clinics1':'Clinics rating 1 of the last visiting clinic',
  'Subscription.Clinics2':'Clinics rating 2 of the last visiting clinic',
  'Subscription.Vet':'Vet clinic check-up',
  'Subscription.Save':'Save',
  'Subscription.notShipped':'not shipped',
  'Subscription.allShipments':'All shipments',
  'Subscription.partialShipment':'Partial shipment',
  'Subscription.invalid':'Invalid',
  'Subscription.unknown':'Unknown',
  'Subscription.SubscriptionDetails':'Subscription Details',
  'Subscription.EnjoyDiscount':'Enjoy discount',
  'Subscription.Amount':'Amount',
  'Subscription.ShipmentDate':'Shipment date',
  'Subscription.OrderStatus':'Order status',
  'Subscription.Total':'Total',
  'Subscription.detail':'Subscription detail',
  'Subscription.SubscriptionNumber':'Subscription Number',
  'Subscription.SubscriptionDate':'Subscription Date',
  'Subscription.AuditorID':'Auditor ID',
  'Subscription.AuditorName':'Auditor Name',
  'Subscription.PetOwnerName':'Pet owner name',
  'Subscription.ConsumerAccount':'Consumer Account',
  'Subscription.ConsumerType':'Consumer type',
  'Subscription.PhoneNumber':'Phone Number',
  'Subscription.BillingAddress':'Billing Address',
  'Subscription.Shipping':'Shipping',
  'Subscription.Tax':'Tax',
  'Subscription.CardNumber':'Card Number',
  'Subscription.IVAInclude':'IVA Include',
  'Subscription.DeliveryAddress':'Delivery Address',
  'Subscription.Name':'Name',
  'Subscription.City':'City',
  'Subscription.State':'State',
  'Subscription.Country':'Country',
  'Subscription.Address1':'Address1',
  'Subscription.Address2':'Address2',
  'Subscription.PaymentMethod':'Payment Method',
  'Subscription.shippingArea':'Address is not within shipping area',
  'Subscription.skipThisItem':'Are you sure to skip this item?',
  'Subscription.edit':'Subscription edit',
  'Subscription.BillingAddressIs':'Billing address is the same as',
  'Subscription.Promotion':'Promotion',
  'Subscription.AddNew':'Add new',
  'Subscription.UnfoldedAll':'Unfolded all delivery addresses',
  'Subscription.SubscriptionPlan':'Subscription Plan',
  'Subscription.SubscriptionPlanID':'Subscription Plan ID',
  'Subscription.SubscriptionPlanName':'Subscription Plan Name',
  'Subscription.PleasePlanType':'Please input Subscription Plan Type',
  'Subscription.EnableLandingPage':'Enable landing page',
  'Subscription.Add':'Add',
  'Subscription.OnceEvery':'Once every',
  'Subscription.Status':'Status',
  'Subscription.Enable':'Enable',
  'Subscription.AddConsents':'Add consents',
  'Subscription.ConsentId':'Consent Id',
  'Subscription.ConsentCode':'Consent code',
  'Subscription.ConsenType':'Consent type',
  'Subscription.Category':'Category',
  'Subscription.FieldType':'Field type',
  'Subscription.AddProducts':'Add products',
  'Subscription.productName':'Product name',
  'Subscription.Consumer':'Consumer',
  'Subscription.brand':'Brand',
  'Subscription.Optional':'Optional',
  'Subscription.Required':'Required',
  'Subscription.ConsentType':'Consent type',
  'Subscription.EmailIn':'Email in',
  'Subscription.EmailOut':'Email out',
  'Subscription.EditPlan':'Edit Plan (Food Dispenser)',
  'Subscription.AddNewPlanFood':'Add New Plan (Food Dispenser)',
  'Subscription.SettingPriceIs':'Setting price is required',
  'Subscription.Return':'Return',
  'Subscription.NextStep':'Next step',
  'Subscription.Publish':'Publish',
  'Subscription.Subscription Number':'Subscription Number',
  'Subscription.Order Number':'Order Number',
  'Subscription.Pet Owner Name':'Pet Owner Name',
  'Subscription.Pet Owner Account':'Pet Owner Account',
  'Subscription.Product Name':'Product Name',
  'Subscription.SKU Code':'SKU Code',
  'Subscription.Receiver':'Receiver',
  'Subscription.Receiver Phone':'Receiver Phone',
  'Subscription.Auditor Name':'Auditor Name',
  'Subscription.Auditor ID':'Auditor ID',
  'Subscription.Pause':'Pause',
  'Subscription.Delivery information':'Delivery information',
  'Subscription.Billing information':'Billing information',
  'Subscription.On':'On',
  "Subscription.Off": 'Off',
  "Subscription.Setting": 'Subscription Setting', 
  "Subscription.Draft": 'Subscription Draft',
  'Subscription.Restart':'Restart',
  'Subscription.ReminderSwitchProduct':'Reminder to switch product (Club)',
  'Subscription.ReminderSwitchProductDesc':'Days before the next lifestage, an email will be sent to pet owners to recommend a new product',
  'Subscription.EmailReminderIntervals':'Email reminder intervals',
  'Subscription.EmailReminderIntervalsDesc':'Attempts between first and last emails due to inventory issues',
  'Subscription.Operator Type':'Operator Type',
  'Subscription.Operator':'Operator',
  'Subscription.Time':'Time',
  'Subscription.Operation Category':'Operation Category',
  'Subscription.Operation Log':'Operation Log',
  
};
