import {FormattedMessage} from "react-intl";
import React from 'react';

/**
 * 多语言英文
 */
export default {
  /*-------------------------------- Public ---------------------------------------------*/
  'Public.overview':'Overview123',
  /*-----------------------------  Home ------ ----------------------------------------*/
  'Home.overview':'Overview',


  /*-----------------------------  Product  ------------------------------------------*/

  /*-----------------------------  Order  --------------------------------------------*/

  /*---order-list-prescriber yxy---*/
  'Order.order': 'order',
  'Order.Orderlist': 'Order list',
  'Order.Ordernumer': 'Order number',
  'Order.Subscriptionumber': 'Subscription number',
  'Order.Petownername': 'Pet owner name',
  'Order.Petowneraccount': 'Pet owner account',
  'Order.Productname': 'Product name',
  'Order.SKUcode': 'SKU code',
  'Order.Recipient': 'Recipient',
  'Order.Recipientphone': 'Recipient phone',
  'Order.Auditorname': 'Auditor name',
  'Order.Auditorid': 'Auditor id',
  'Order.Paymentstatus': 'Payment status',
  'Order.Shippingstatus': 'Shipping status',
  'Order.OrderCategory': 'Order Category',
  'Order.Startdate': 'Start date',
  'Order.Enddate': 'End date',
  'Order.Recommendername': 'Recommender name',
  'Order.Recommenderid': 'Recommender id',
  'Order.Bulkoperations': 'Bulk operations',
  'Order.BatchExport': 'Batch Export',
  'Order.Exportfilteredorders': 'Export filtered orders',
  'Order.Exportselectedorders': 'Export selected orders',
  'Order.Pendingreview': 'Pending review',
  'Order.Tobedelivered': 'To be delivered',
  'Order.Tobereceived': 'To be received',
  'Order.Completed': 'Completed',
  'Order.Outofdate': 'Out of date',
  'Order.Product': 'Product',
  'Order.Amount': 'Amount',
  'Order.Quantity': 'Quantity',
  'Order.Seedetails': 'See details',
  'Order.DeliveryRecord': 'Delivery Record',
  'Order.Ordertime': 'Order time',
  'Order.Order.Consumertype:  Member': 'Consumer type:  Member',
  'Order.Consumertype': 'Consumer type',
  'Order.Phonenumber': 'Phone number',
  'Order.ProductName': 'Product Name',
  'Order.Weight': 'Weight',
  'Order.Price': 'Price',
  'Order.Subtotal': 'Subtotal',
  'Order.Productamount': 'Product amount',
  'Order.Shippingfees': 'Shipping fees',
  'Order.Total': 'Total',
  'Order.DeliveryCountry': 'Delivery Country',
  'Order.DeliveryInvoiceaddress1': 'Delivery Invoice address1',
  'Order.DeliveryCity': 'Delivery City',
  'Order.DeliveryInvoiceaddress2': 'Delivery Invoice address2',
  'Order.Deliveryaddress1': 'Delivery address1',
  'Order.Deliveryaddress2': 'Delivery address2',
  'Order.Postalcode': 'Postal code',
  'Order.Reference': 'Reference',
  'Order.Deliverycomment': 'Delivery comment',
  'Order.Operationlog': 'Operation log',
  'Order.OperatorType': 'Operator Type',
  'Order.Operator': 'Operator',
  'Order.Time': 'Time',
  'Order.OperationCategory': 'Operation Category',
  'Order.OperationLog': 'Operation Log',
  'Order.No.': 'No.',
  'Order.Shipped': 'Shipped',
  'Order.ThisShipment': 'This Shipment',
  'Order.PaymentRecords': 'Payment Records',
  'Order.Amountreceivable': 'Amount receivable',
  'Order.CollectionSerial Number': 'Collection Serial Number',
  'Order.CollectionTime': 'Collection Time',
  'Order.AmountReceived': 'Amount Received',
  'Order.AccountsReceivable': 'Accounts Receivable',
  'Order.Accessories': 'Accessories',
  'Order.Status': 'Status',
  'Order.Remarks': 'Remarks',
  'Order.Operatio': 'Operation',
  'Order.PaymentId': 'Payment Id',
  'Order.PaymentTime': 'Payment Time',
  'Order.Name': 'Name',
  'Order.Email': 'Email',
  'Order.Cardnumber': 'Card number',
  'Order.Paymentmethod': 'Payment method',
  'Order.Comment': 'Comment',
  'Order.Pleaseinputcomment': 'Please input comment',
  'Order.AddComment': 'Add Comment',
  'Order.Edit': 'Edit',
  'Order.Delete': 'Delete',
  'Order.Pleaseselecttheorder': 'Please select the order that needs to be operated',
  'Order.Audit': 'Audit',
  'Order.Confirmtoreview?': 'Confirm to review the selected order?',
  'Order.Batchreview': 'Batch review',
  'Order.Batchexport': 'Batch export',
  'Order.Consumername': 'Consumer name',
  'Order.Consumeraccount': 'Consumer account',
  'Order.Unpaid': 'Unpaid',
  'Order.Paid': 'Paid',
  'Order.All': 'All',
  'Order.Tobeconfirmed': 'To be confirmed',
  'Order.Paying': 'Paying',
  'Order.notshipped': 'not shipped',
  'Order.Partialshipment': 'Partial shipment',
  'Order.Allshipments': 'All shipments',
  'Order.Singlepurchase': 'Single purchase',
  'Order.1stautoshiporder': '1st autoship order',
  'Order.Recurrentorders of autoship': 'Recurrent orders of autoship',
  'Order.Export': 'Export',
  'Order.Cancel': 'Cancel',
  'Order.Pleaseselectanexportmethod': 'Please select an export method',

  /*-----------------------------  Task  ----------------------------------------------*/

  /*-----------------------------  Subscription  ---------------------------------------*/

  /*-----------------------------  Pet owner  ----------------------------------------*/

  /*-----------------------------  Finance  ------------------------------------------*/

  /*-----------------------------  Marketing  ----------------------------------------*/

  /*-----------------------------  Prescriber  ----------------------------------------*/

  /*-----------------------------  Analysis  ----------------------------------------*/

  /*-----------------------------  Content  ----------------------------------------*/

  /*-----------------------------  Setting  ----------------------------------------*/




  /*---------------------------------------------------------------------*/
  name: 'Name',
  stock: 'Stock',
  giveaway: 'Giveaway',
  addProduct: 'Add product',
  brand: 'Brand',
  catogery: 'Catogery',
  enterUpTo100Characters: 'Enter up to 100 characters',
  fillInTheRemarks: 'Fill in the remarks',
  address: 'Address',
  extraInformation: 'Extra information',
  inputPhoneNumberTip: 'Please enter the phone number',
  inputPhoneNumberTip2: 'Please enter the correct phone number',
  more: 'More',
  receiver: 'Receiver',
  defaultAddress: 'Default address',
  phoneNumber2: 'Phone number',
  piece: 'Piece',
  total: 'Total',
  all: 'All',
  edit: 'Edit',
  description: 'description',
  operation: 'Operation',
  details: 'Details',
  delete: 'Delete',
  editProduct: 'Edit product',
  basicInformation: 'Basic information',
  priceAndOrderAmount: 'Price and order amount',
  basePrice:'Base price',
  operationInstruction: 'Operation instruction',
  allTheSame: 'All the same',
  'operationInstruction.first':
    'Until filled all required fields, the product could be published. ',
  'operationInstruction.second':
    ' The product information tab, product price tab, product inventory tab must be filled before published.',
  'operationInstruction.third':
    'If you do not need to set the related product or SEO, you can click \'Next\' directly after editing the inventory information.',
  'product.product': 'Product',
  'product.productList': 'Product list',
  'product.productName': 'Product name',
  'product.SPU': 'SPU',
  'product.SKU': 'SKU',
  "product.purchasePrice": "Purchase price",
  'product.productCategory': 'Product category',
  'product.storeCategory': 'Store category',
  'product.salesCategory': 'Sales category',
  'product.brand': 'Brand',
  'product.search': 'Search',
  'product.batchOperation': 'Batch operation',
  'product.onShelves': 'On shelves',
  'product.partialOnShelves': 'Partial on shelves',
  'product.offShelves': 'Off shelves',
  'product.image': 'Image',
  'product.linePrice': 'Line price',
  'product.listPrice': 'List price',
  'product.onOrOffShelves': 'On/off shelves',
  'product.setPrice': 'Set price',
  'product.editProduct': 'Edit product (Bundle product)',
  'product.basicInformation': 'Basic information',
  'product.priceAndOrderAmount': 'Price and order amount',
  'product.operationInstruction': 'Operation instruction',
  'product.platformCategory': 'Signed classification',
  'product.productSubtitle': 'Product subtitle',
  'product.unitMeasurement': 'Unit measurement',
  'product.productDescription': 'Product description',
  'product.marketPrice': 'Market price',
  'product.productImage': 'Product image',
  'product.productVideo': 'Product video',
  'product.recommendedSizeImg':
    'If the sales category is set to display in shop, the first picture is showed in the hompage and the next picture is showed in the product list page.',
  'product.recommendedSizeVideo':
    'Product video size is recommended 30M, the maximum limit is 50M, supported file type is mp4, recommended duration is less than or equal to 90s, greater than or equal to 6s, recommended video ratio of 7: 9',
  'product.attributeInformation': 'Attribute information',
  'product.recommendedAliasName':'English name of sales category for searching specific type producy,  you need to create Alias name in dictionary first, and then choose from.',
  'product.recommendedRouter':'The router could be customized by business needs, which show in the shop when select relevant sales category. In shop, the router should be like this"/"any letters"/?prefn1={attribute name}&prefv1={Attibute value1}|{Attribute value2}|{Attribute valuen},{}should be replace with real content of attribute.For example /cats/?prefn1=ages&prefv1=Adulte (1-7 ans)|Mature (7-12 ans)|Senior (+ 12 ans)',

  'product.attributeInformationDetail':
    'Consumber can filter the products according to the attributes. If attributes are not filled in or filled in incorrectly, the products may not be found and affect your sales. Please input carefully and accurately',
  'product.specificationSetting': 'Specification setting',
  'product.setMultipleSpecificationOfProducts':
    'Set multiple specification of products',
  'product.inventory': 'Inventory',
  'product.logisticsInformation': 'Logistics information',
  'product.shippinTemplate': 'Shipping template',
  'product.logisticsWeight': 'Logistics weight',
  'product.logisticsVolumn': 'Logistics volumn',
  'product.productDetail': 'Product detail',
  'product.saveDirectly': 'Publish directly',
  'product.next': 'The next step',
  'product.publishDirectly': 'Publish directly',
  'product.productTemplateImport': 'Product template import',
  'product.productPoolImport': 'Product pool import',
  'product.publishItemInfo1': 'Publish directly delicacy managment',
  'product.publishItemInfo2': 'Excel file quick import',
  'product.publishItemInfo3': 'One-click import of platform commodity library',
  'product.postGoods': 'Publish product',
  'product.InternalSPU': 'Internal SPU',
  'product.InternalSKU': 'Internal SKU',
  'product.chooseAPublishingMethod': 'Choose a publishing method',
  'product.storeCategoryInfo':
    'Store category is the classification of products within the scope of your store. Up to 2 levels can be added. When there is No categories, all products will be classified into the default classification',
  'product.salesCategoryInfo':
    'Sales category is the classification of products within the scope of your store. Up to 3 levels can be added. When there is No categories, all products will be classified into the default classification',
  'product.addFirstLeverCate': 'Add the first group',
  categoryName: 'Category name',
  addSubcategory: 'Add subcategory',
  'product.importInfo1':
    'Please download the product import template first, and input the product data according to the requirements in the annotation. Failure to input the requirements will cause the product import to fail.',
  'product.importInfo2':
    'Please choose .xlsx or .xls file, the file size is ≤ 2M, only one file can be imported at a time, it is recommended that no more than 500 product data are imported at a time.',
  'product.downloadProductImportTemplate': 'Download product import template',
  productImport: 'Product import',
  uploadData: 'Upload data',
  uploadDataInfo: 'Upload data',
  finish: 'Finish',
  chooseFileToUpload: 'Choose file to upload',
  confirmToImport: 'Confirm to import',
  subCategory: 'Sub-category',
  pendingProducts: 'Pending',
  batchDeletion: 'Batch deletion',
  pendingReview: 'Pending review',
  reviewFailed: 'Review failed',
  banned: 'Banned',
  reason: 'Reason',
  priceSettingMethod: 'Price setting method',
  approvalStatus: 'Approval status',
  commodityLibraryImport: 'Commodity library import',
  commodityLibraryImportInfo:
    'The products imported from the commodity library are initially reviewed / off the shelf. Please add the information before selling them;',
  instructions: 'Instructions:',
  status: 'Status',
  batchImport: 'Batch Import',
  addSpecifications: 'Specification setting',
  newProduct: 'New product (Bundle product)',
  email: 'Email',
  basicSetting: 'Basic setting',
  storeSetting: 'Store setting',
  storeLogo: 'Store logo',
  shopLogo: 'Shop logo',
  storeNumber: 'Store number',
  storeAccount: 'Store account',
  storeName: 'Store name',
  Contact: 'Contact',
  phoneNumber: 'Phone number',
  contactEmails: 'Contact emails',
  shop: 'Shop',
  storeSettingInfo1:
    'PC mall home page logo, mobile terminal login page logo, management terminal logo, up to 1 can be added, only jpg, jpeg, png, gif, recommended size 100px * 100px, size not more than 1M',
  storeSettingInfo2:
    'PC mall store shop, you can add up to one, the picture format is limited to jpg, jpeg, png, gif, the recommended size is 1920px * 120px, and the size does not exceed 2M',
  storeInformation: 'Shop information',
  businessInformation: 'Business information',

  ssoSetting: 'SSO setting',
  logIn: 'Log in',
  userinfoURL: 'Userinfo URL',
  clientID: 'Client id',
  issuer: 'Issuer',
  pedirectURL: 'Pedirect url',
  registration: 'Registration',
  registerPrefix: 'Register prefix',
  registerCallback: 'Register callback',

  storeInformationEdit: 'Shop Information Edit',
  footer: 'Footer',
  consent: 'Consent',
  confirmationEmail: 'Confirmation email',
  faqUrl: 'FAQ(URL)',
  privacyPolicy: 'Privacy policy',
  termsOfUse: 'Terms of use',
  cookies: 'Cookies collection policy/Cookie',
  storeContactPhoneNumber: 'Contact phone',
  storeContactEmail: 'Contact email',
  customerServiceEamil: 'Customer Service Eamil',
  contactTimePeriod: 'Contact period',
  contactUsUrl: 'About us',
  legalTerms: 'Legal terms',
  ourValues: 'Our values',
  qualityAndSafety: 'Quality and safety',
  specificNutrition: 'Specific nutrition',
  informationForParents: 'Information for parents',
  signedInformation: 'Signed information',
  financialInformation: 'Financial Information',
  reviewStatus: 'Review status',
  storeStatus: 'Shop status',
  partnerNumber: 'Partner number',
  partnerName: 'Partner name',
  contact: 'Contact',
  contactDetails: 'Contact details',
  contactEmail: 'Contact email',

  paymentSetting: 'Payment setting',
  environment: 'Environment',
  URL: 'URL',
  appID: 'APP ID',
  apiKey: 'API Key',
  privateKey: 'Private key',
  publicKey: 'Public key',
  apiVersion: 'API version',
  bannerNo: 'Banner No',
  partnerAccount: 'Partner account',
  employeeList: 'User list',
  employeeName: 'User name',
  employeePhone: 'User phone',
  employeeEmail: 'User email',
  employeeNo: 'User No.',
  roles: 'Roles',
  supervisor: 'Supervisor',
  assistant: 'Assistant',
  whetherToActivateTheMemberAccount: 'Whether to activate the member account',
  add: 'Add',
  position: 'Position',
  systemRole: 'System Role',
  clinics: 'Clinics',
  Prescriber: 'Prescriber',
  hideLeavingEmployees: 'Hide leaving Users',
  attributionDepartment: 'Attribution Group',
  allDepartment: 'All Group',
  departmentManagement: 'Group management',
  departmentManagementInfo1:
    'During initialization, it can be imported by using the "Detach creation" department;',
  departmentManagementInfo2:
    'Support drag and drop between departments at the same level;',
  departmentManagementInfo3:
    'Each department can set up a supervisor, the supervisor can see and manage the employees of his department and sub-departments, and the supervisor has all the data permissions of the salesmen of his department and his sub-departments;',
  departmentName: 'Group name',
  supervivor: 'Supervivor',
  employeeNumber: 'User number',
  addDetachDepartments: 'Add detach group',
  rolePermissions: 'Role permissions',
  addRole: 'Add role',
  roleName: 'Role name',
  permission: 'Permission',
  setPermission: 'Set permission',
  assetManagement: 'Asset management',
  imageAsset: 'Image asset',
  videoAsset: 'Video asset',
  imageContent: 'Image content',
  videoContent: 'Video content',
  move: 'Move',
  selectAll: 'Select all',
  uploadImage: 'Upload image',
  uploadVideo: 'Upload video',
  addCategory: 'Add category',
  videoName: 'Video name',
  videoUrl: 'Video link',
  operatorAccount: 'Operator account',
  operatorName: 'Operator name',
  operatorContent: 'Operator content',
  operatorTime: 'Operator time',
  operatorIP: 'Operator IP',
  module: 'Module',
  export: 'Export',
  assetCategory: 'Asset category',
  assetCategoryInfo:
    'Asset category can add up to 3 levels, when there is nocategory, all asset will be classified into the default category',
  unifiedSocialCreditCode: 'Unified Social Credit Code',
  enterpriseName: 'Enterprise name',
  legalRepresentative: 'Legal representative',
  registeredCapital: 'Registered capital',
  establishmentDate: 'Establishment Date',
  businessPeriodSince: 'Business period since',
  businessPeriodTo: 'Business period to',
  businessScope: 'Business Scope',
  electronicCopyOfBusinessLicense: 'Electronic copy of business license',
  corporateIdentityCard: 'Corporate identity card',
  signedCategory: 'Signed product category',
  signedCategoryInfo:
    'categories have been signed, the maximum is 200 categories',
  superiorCategory: 'Parent category',
  categoryDeductionRate: 'Category deduction rate',
  businessQualification: 'Business qualification',
  settlementDate: 'Settlement date',
  settlementDateInfo1:
    'settlement days have been added, the maximum is 5 settlement days',
  everyMonth: 'Every month',
  settlementDateInfo2:
    'When the month does not include the set date, it will be postponed to the next settlement date',
  day: 'Day',
  settlementBankAccount: 'Settlement bank account',
  settlementDateInfo3:
    'settlement days have been added, the maximum is 5 settlement days.If you need to modify the settlement account, please operate in the finance module',
  'No.': 'No.',
  bank: 'Bank',
  account: 'Account',
  'sub-branch': 'Sub-branch',
  mainAccount: 'Main account',
  settlement: 'Settlement',
  SettlementStatementTime: 'Settlement statement time',
  SettlementPeriod: 'Settlement period',
  Paymentamount: 'Payment amount',
  product: 'Product',
  consumerList: 'Consumer list',
  consumerClinicList: 'Consumer list(Presciber)',
  consumerName: 'Consumer name',
  area: 'Area',
  targetCountry: 'Target country',
  targetCity: 'Target city',
  storeLanguage: 'Shop language',
  timeZone: 'Time zone',
  currency: 'Currency',
  domainName: 'Domain name',
  miniCharge: 'Minimum charge',
  prescriberMap: 'Prescriber Map',
  profilePaymentMethod: 'Profile-Payment Method',
  onePageCheckout:'One-Page Checkout',
  taxRate: 'Tax rate',
  detailAddress: 'Detail address',
  selectAddress: 'Please select an address',
  consumerType: 'Consumer type',
  platformLevel: 'customer Level',
  accountStatus: 'Account status',
  accountNumber: 'Account Number',
  auditors: 'Auditors',
  search: 'Search',
  audited: 'Audited',
  contactPerson: 'Contact Person',
  contactPhoneNumber: 'Contact phone number',
  tourist: 'Tourist',
  platformConsumers: 'Platform Consumers',
  enable: 'Enable',
  disabled: 'Disabled',
  enabled: 'Enabled',
  consumerLevel: 'Consumer type',
  levelName: 'Type name',
  levelBadge: 'Type badge',
  view: 'View',
  noData: 'no data',
  save: 'Save',
  cancel: 'Cancel',
  orderDetails: 'Order Details',
  deliveryRecord: 'Delivery Record',
  collectionRecords: 'Payment Records',
  toBeDelivered: 'To be delivered',
  ship: 'Ship',
  orderNumber: '   Order number  ',
  payWay: 'Pay Way',
  consumer: 'Consumer',
  consumerAccount: 'Consumer account',
  consumerInfo: 'Consumer information',
  orderTime: 'Order time',
  skuCode: 'SKU code',
  spuCode: 'SPU code',
  productName: 'Product name',
  weight: 'Weight',
  price: 'Price',
  memberPrice: 'member price',
  quantity: 'Quantity',
  subtotal: 'Subtotal',
  productAmount: 'Product amount',
  fullReductionAmount: 'Full reduction amount',
  fullDiscountAmount: 'Full discount amount',
  promotionAmount: 'Promotion amount',
  fullDiscount: 'Full discount',
  coupon: 'Coupon',
  pointsDeduction: 'Points deduction',
  shippingFees: 'Shipping fees',
  tax: 'Tax',
  totalPayable: 'Total payable',
  sellerNotes: 'Seller notes',
  buyerNotes: 'Buyer notes',
  orderAttachment: 'Order attachment',
  none: 'none',
  paymentMethod: 'Payment method',
  onlinePayment: 'online payment',
  offlinePayment: 'Offline payment',
  generalInvoice: 'General invoice ',
  invoiceReceivingAddress: 'Invoice receiving address',
  deliveryMethod: 'Delivery method',
  expressDelivery: 'Express delivery',
  deliveryInformation: 'delivery information',
  confirm: 'Confirm',
  productFirstLetterUpperCase: 'Product',
  recipient: 'Recipient',
  recipientPhone: 'Recipient phone',
  amount: 'Amount	',
  cateImage: 'Category image',
  cateDsc: 'Category description',

  'order.orderList': 'Order list',
  'order.orderNumber': 'Order number',
  'order.subscriptioNumber': 'Subscription number',
  'order.shippingStatus': 'Shipping status',
  'order.paymentStatus': 'Payment status',
  'order.orderStatus': 'Order status',
  'order.orderSource': 'Order source',
  'order.startDate': 'Start date',
  'order.endDate': 'End date',
  'order.bulkOperations': 'Bulk operations',
  'order.pendingReview': 'Pending review',
  'order.toBeFormed': 'To be formed',
  'order.notShipped': 'not shipped',
  'order.toBeDelivered': 'To be delivered',
  'order.toBeReceived': 'To be received',
  'order.paid': 'Paid',
  'order.unpaid': 'Unpaid',
  'order.toBeConfirmed': 'To be confirmed',
  'order.received': 'Received',
  'order.confirmReceipt': 'Confirm receipt',
  'order.completed': 'Completed',
  'order.outOfDate': 'Out of date',
  'order.ship': 'Ship',
  'order.allShipments': 'All shipments',
  'order.partialShipment': 'Partial shipment',
  'order.invalid': 'Invalid',
  'order.unknown': 'Unknown',
  'order.seeDetails': 'See details',
  'order.PCOrder': 'PC order',
  'order.H5Order': 'H5 order',
  'order.AppOrder': 'APP order',
  'order.miniProgramOrder': 'Mini Program order',
  'order.rejectionReasonTip': 'Please enter the reason for rejection',
  'order.100charactersLimitTip': 'Please input less than 100 characters',
  'order.valetOrder': 'Valet order',
  'order.fightTogether': 'Fight together',
  'order.audit': 'Audit',
  'order.turnDown': 'Turn down',
  'order.review': 'Review',
  'order.confirmReceivedAllProducts':
    'Confirm that all products have been received?',
  'order.confirmReview':
    'Are you sure you want to return the selected order for reconsideration?',
  'order.confirmAudit': 'Confirm to review the selected order?',
  'order.exportFilterOrder': 'Export filtered orders',
  'order.exportSelectedOrder': 'Export selected order',
  'order.pleaseSelectOrderToOperate':
    'Please select the order that needs to be operated',
  'order.batchReview': 'Batch review',
  'order.batchExport': 'Batch export',
  'order.editOrder': 'Edit order',
  'order.mustSelectAMember': 'Must select a member',
  'order.noAddressAvailable':
    'No address available, please input temporary address',
  'order.mustChooseAShippingAddress': 'Must choose a shipping address',
  'order.pleaseSelectProvinceOrCityOrDistrict':
    'Please select province/city/district',
  'order.inputDetailAddressTip1': 'Please input the detailed address',
  'order.inputDetailAddressTip2':
    'Detailed address length must be between 5-60 characters',
  'order.inputReceiverTip': 'Please input the receiver',
  'order.uploadValidateTip':
    'Supported picture formats: jpg, jpeg, png, gif, file size no more than 5M, maximum upload 10',
  'order.uploadValidateTip2': 'Image size cannot exceed 5MB',
  'order.orderPriceChange': 'Order price change',

  'invoice.invoiceInformation': 'Invoice information',
  'invoice.noInvoiceRequired': 'No invoice required',
  'invoice.personal': 'Personal',
  'invoice.company': 'Company',
  'invoice.pleaseSelectInvoiceItem': 'Please select invoice item',
  'invoice.mustSelectInvoiceItem': 'Must select invoice item',
  'invoice.invoiceHeader': 'Invoice header',
  'invoice.mustFillInTheInvoiceHeader': 'Must input the invoice header',
  'invoice.invoiceHeaderValidateTip1':
    'Invoice header must be at least 1 character',
  'invoice.invoiceHeaderValidateTip2':
    'Invoice header can enter up to 50 characters',
  'invoice.taxpayerIdentificationNumber': 'Taxpayer Identification Number',
  'invoice.taxpayerIdentificationNumberValidateTip':
    'Please enter the correct taxpayer identification number and must be 15-20 characters',
  'invoice.taxpayerIdentificationNumberValidateTip2':
    'Wrong filling will not be used as tax certificate or cannot be reimbursed',
  'invoice.companyFullName': 'Full name of company',
  'invoice.companyTaxpayerIdentificationNumber':
    'Company taxpayer identification number',
  'invoice.companyPhone': 'Company phone ',
  'invoice.basicBankAccountNumber': 'Basic bank account number',
  'invoice.bank': 'Bank',
  'invoice.useSeparateInvoiceReceiptInformation':
    'Use separate invoice receipt information',

  operationLog: 'Operation log',
  operatorType: 'Operator type',
  operator: 'Operator',
  time: 'Time',
  operationCategory: 'Operation category',
  paymentOrder: 'Payment order',
  createOrder: 'Create Order',
  order: 'Order',
  back: 'Back',

  initiateApplication: 'Initiate after-sales application',
  amountQuantity: 'Amount (Quantity)',
  shippingStatus: 'Shipping status',
  orderStatus: 'Order status',
  paymentStatus: 'Payment status',
  notShipped: 'Not shipped',
  application: 'Application',
  newChargeback: 'New chargeback',
  refundInformation: 'Refund information',
  refundReason: 'Refund reason',
  selectRefundReacon: 'Please select the reason for refund',
  returnInstructions: 'Return instructions',
  attachmentInformation: 'Attachment information',

  attachmentTips:
    'Please add your return receipt to the attachment, the supported picture formats: jpg, jpeg, png, gif, the file size does not exceed 5M, and the maximum upload is 10',
  refundableAmount: 'Refundable amount',
  pointsRefundable: 'Points refundable',
  commodity: 'Commodity',
  refundList: 'Refund list',
  chargebackNumber: 'Chargeback number',
  refundTime: 'Refund time',
  chargebackStatus: 'Chargeback status',
  actualRefundAmount: 'Actual refund amount',
  actualRefundPoints: 'Actual refund points',
  toBeFilledOutLogisticsInformation: 'To be filled out logistics information',
  waitingForTheMerchantToReceiveTheGoods:
    'Waiting for the merchant to receive the goods',
  pendingRefund: 'Pending refund',
  rejected: 'Rejected',
  refusedToRefund: 'Refused to refund',
  refundFailed: 'Refund failed',
  refund: 'Refund',
  realRefund: 'Real refund',
  refundDetails: 'Refund details',
  applicationTime: 'Application time',
  chargeback: 'Chargeback',
  returnUnitPrice: 'Return unit price',
  quantityReturned: 'Quantity returned',
  subtotalOfReturnAmount: 'Subtotal of return amount',
  Refund: 'Refund',
  returnReason: 'Return reason',
  chargebackAttachment: 'Chargeback attachment',

  financeTips1:
    '1. The platform will make a small amount of money for the bank account you created for the first time. After the platform makes a payment, you can see the button to receive the money, and your account will only take effect after confirmation;',
  financeTips2:
    '2. You can set any account that passes the verification as the main account, and the platform will give priority to the main account when you settle the payment;',

  petFoodStore: 'Pet food store',
  entryTime: 'Entry time',
  partnerID: 'Partner ID',
  contractValidity: 'Contract validity',
  addAccount: 'Add Account',
  accountName: 'Account name',
  subBranch: 'Sub-branch',
  receivePayment: 'Receive payment',

  changeAccount: 'Change the current account',
  deleteAccount: 'Delete account',
  setMainAccount: 'Set the main account',

  financialReconciliation: 'Finance reconciliation',
  bulkExport: 'Bulk export',
  revenueReconciliation: 'Revenue reconciliation',
  refundReconciliation: 'Refund reconciliation',
  VISA: 'VISA',
  'AMERICAN EXPRESS': 'AMERICAN EXPRESS',
  masterCard: 'MasterCard',

  balance: 'Balance',
  total2: 'total',
  revenueReconciliationDetails: 'Revenue Reconciliation Details',
  paymentChannel: 'Payment Channel',
  transactionSerialNumber: 'Transaction Serial Number',
  serialNumber: 'Serial number',
  paymentTime: 'Payment Time',
  paymentAmount: 'Payment amount',
  paymentNumber: 'Payment number',
  paymentId: 'Payment Id',
  financialSettlement: 'Finance settlement',
  settlementTips1: 'Your settlement date is',
  settlementTips2:
    'th of each month, when the month does not include the set date, it will be postponed to the next settlement date',

  unSettlement: 'Unsettlement',
  settled: 'Settled',
  statementGenerationTime: 'Statement Generation Time',
  statementTime: 'Statement Time',
  statementNumber: 'Statement number',
  statementPeriod: 'Statement period',

  billingPeriod: 'Billing Period',
  totalPaidGoods: 'Total Paid Goods',
  totalFreight: 'Total Freight',

  inquiryDetails: 'Details',
  settlementDetails: 'Settlement Details',
  exportDetails: 'Export Details',

  orderCreditTime: 'Order Credit Time',
  orderType: 'Order Type',
  // 'Product code / name / weight':'商品编码/名称/规格'	,
  category: 'Category',
  productPrice: 'Product Price',
  freight: 'Freight',
  //财务
  //Finance Reward
  Reward: 'Reward',
  orderInvoice: 'Order Invoice',
  PrescriberID: 'Prescriber id',
  PrescriberName: 'Prescriber name',
  BulkExport: 'Bulk export',
  Refresh: 'Refresh',
  PrescriberType: 'Prescriber type',
  OrderQuantity: 'Order quantity',
  OrderAmount: 'Order amount',
  RewardType: 'Reward type',
  RewardAmount: 'Reward amount',
  Operation: 'Operation',

  //Finance Reward-Details
  rewardDetails: 'Reward Details',
  RewardRules: 'Reward Rules',
  OrderNumber: 'Order number',
  OrderTime: 'Order Time',
  RewardRate: 'Reward Rate',
  RewardRemark: 'Reward Remark',

  firstRewardRate: 'First Reward Rate',
  repeatRewardRate: 'Repeat Reward Rate',

  invoiceStatus: 'Invoice Status',

  bulkOperation: 'Bulk Operation',
  bulkInvoice: 'Bulk Invoice',

  billingTime: 'Billing Time',
  orderAmount: 'Order amount',
  invoiceType: 'Invoice Type',

  ordinaryInvoice: 'Ordinary invoice',
  personal: 'Personal',
  toBeInvoiced: 'To be invoiced',
  viewBilling: 'View Billing',
  billingItems: 'Billing Items',

  supportedBillingTypes: 'Supported billing types',
  doesNotSupportInvoicing: 'Does not support invoicing',

  vatSpecialInvoice: 'VAT special invoice',
  saveSettings: 'Save Settings',
  Edit: 'Edit',
  Delete: 'Delete',

  customerAccount: 'Customer Account',
  clinicName: 'Auditor name',
  clinicID: 'Auditor id',

  recommenderId:'Recommender id',
  recommenderName:'Recommender name',
  deliveryCountry: 'Delivery Country',
  deliveryCity: 'Delivery City',
  deliveryAddress1: 'Delivery address1',
  deliveryAddress2: 'Delivery address2',
  postalCode: 'Postal code',
  reference: 'Reference',
  deliveryComment: 'Delivery comment',
  deliveryInvoiceAddress1: 'Delivery Invoice address1',
  deliveryInvoiceAddress2: 'Delivery Invoice address2',
  cardNumber: 'Card number',
  selectedPrescriberId: 'Selected Prescriber id',
  prescriberId: 'Prescriber id',
  prescriberName: 'Prescriber name',
  prescriberPhone: 'Prescriber phone',
  prescriberZip: 'Prescriber zip',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  surveyManage: 'Survey management',
  overview: 'Overview',
  overallRating: 'Overall rating',
  productRating: 'Shopping rating',
  npsDesc1:
    'Description: Survey overview shows the summary of service survey data in the past 180 days',
  ratingWithComment: 'Rating with comment',
  rating: 'Rating',
  allSurvey: 'All survey',
  surveyTime: 'Survey time',
  defaultPrescriberName: 'default Prescriber Name',
  'consumer.consumerDetails': 'Consumer Details',
  'consumer.removeConsumer': 'Remove Consumer',

  shopping: 'Shopping',
  overall: 'Overall',

  toBePaidOrders: 'To be paid orders',
  toBeDeliveredOrders: 'To be delivered orders',
  toBeReceivedOrders: 'To be received orders',
  totalNumber: 'Total number',
  activeNumber: 'Active number',
  visitsToday: 'Visits today',
  transactionToday: 'Transaction today',
  consumerToday: 'Active consumer today',
  productToday: 'Product today',
  visitsReportNearly10Days: 'Visits report nearly 10 days',
  visitsTrendNearly10Days: 'Visits trend nearly 10 days',
  transactionReportNearly10Days: 'Transaction report nearly 10 days',
  transactionTrendNearly10Days: 'Transaction trend nearly 10 days',
  consumerReportNearly10Days: 'Active consumer report nearly 10 days',
  consumerTrendNearly10Days: 'Active consumer trend nearly 10 days',
  totalcConsumerNumber: 'Total active consumer number',
  newConsumerNumber: 'New active consumer number',
  totalSKU: 'Total sku',
  productsOnShelvesNumber: 'Products on shelves number',
  'member number': 'memberNumber',
  uv: 'UV',
  pv: 'PV',
  numberOfPaymentOrders: 'Number of payment orders',
  rewardSummary: 'Reward summary',
  rewardAmount: 'Reward amount',
  items: 'Items',
  'product.subscriptionStatus': 'Subscription status',
  'product.subscriptionPrice': 'Subscription Price',
  'product.defaultPurchaseType': 'Default purchase type',
  'product.defaultFrequency': 'Default frequency',

  'subscription.subList': 'Subscription list',
  'subscription.orderNumber': 'Order number',
  'subscription.consumerName': 'Consumer name',
  'subscription.productName': 'Product name',
  'subscription.deliveryDate': 'Delivery date',
  'subscription.frequency': 'Frequency',
  'subscription.receiver': 'Receiver',
  'subscription.orderData': 'Subscription order date',
  'subscription.quantity': 'Quantity',
  'subscription.notYet': 'Not Yet Shipped',
  'subscription.nextOrder': 'Next Order',
  'subscription.order': 'Order',
  'subscription.total': 'Total',
  'subscription.totalInclu': 'Total(Inclu IVA)',
  'subscription.saveDiscount': 'Subscription Save Discount',
  'subscription.shipping': 'Shipping',
  'subscription.shippingAddress': 'Shipping address',
  'subscription.BillingAddress': 'Billing address',
  'subscription.paymentMethod': 'Payment method',
  'subscription.change': 'change',
  'subscription.product': 'Product',
  'subscription.number': 'Subscription number',
  'subscription.subscriptionNumberTip': 'Please enter subscription number',
  'subscription.date': 'Subscription date',
  'subscription.nextDeliveryDate': 'Next delivery date',
  'subscription.detail': 'Subscription detail',
  'subscription.edit': 'Subscription edit',
  'subscription.sub': 'Sub-',
  'subscription.operation': 'Operation',
  'subscription.subscriptionDate': 'Subscription date',
  items: 'Items',
  petCategory: 'Pet Category',
  petName: 'Pet Name',
  gender: 'Gender',
  breed: 'Breed',
  birthday: 'Birthday',
  specialNeeds: 'Special needs',
  sterilizedStatus: 'Sterilized status',
  //
  reviewManagement: 'Review management',
  // 'overview': 'Overview',
  // 'overallRating': 'Overall rating',
  productRatings: 'Product rating',
  experienceRating: 'Purchase experience rating',
  logisticRating: 'Logistic rating',
  rate: 'Rate',
  star: 'star',
  yes: 'Yes',
  no: 'No',
  description: '',
  reviewTip:
    'Review overview shows the summary of review data in the past 180 days',
  ratingRule: 'Rating rule',
  consumerNumber: 'Consumer number',
  // 'consumerAccount': 'Consumer account',
  displayStatus: 'Display status',
  anonymousStatus: 'Anonymous status',
  reviewList: 'Review list',
  // 'productName': 'Product name',
  // 'consumerName': 'Consumer name',
  reviewTime: 'Review time',
  reviewDetail: 'Review details',
  // 'operation': 'Operation',
  // 'view': 'View',
  // 'delete': 'Delete',
  comments: 'Comments',
  replyComments: 'Reply comments',
  enter500: 'Enter up to 500 characters',
  shopRatingDetail: 'Shop evaluation details',
  evaluationNextDay: 'The store evaluation data will be updated the next day',
  lastest180: 'lastest 180 day',
  detailScore: '{name} score',
  averageScore: 'Average score',
  evaluationHistory: 'Evaluation history',

  subscriptionList: 'Subscription list',
  setBanner: 'Set banner',
  addressManagement: 'Address Management',
  pc: 'PC',
  mobile: 'Mobile',
  preview: 'Preview',
  last180: 'last 180 day',
  ChooseUploadType: ' Choose upload type',
  image: 'Image',
  upload: 'Upload',
  video: 'Video',
  resource: '{type} resource',
  bannerUrl: '{type} Url',
  selectResource: 'Select {type} resource',
  dragImagesOrVideos: 'Click or drag images or videos to upload',
  supportUpload: 'Support one or more pictures or videos upload',
  action: 'Action',
  resourceName: 'Mobile resource',
  Instructions: 'Instructions',
  amountReceivable: 'Amount receivable',
  freightTemplate: 'Freight template',
  storeShipping: 'Store shipping',
  singleProductShipping: 'Single product shipping',
  firstName: 'First name',
  lastName: 'Last name',
  footerConfig:'Footer Config',
  seoSetting: 'SEO Setting',
  siteMap: 'Site map',
  export: 'Export'
};
