import es_ES from './es_ES';

/**
 * 多语言土耳其
 */
export default {
    ...es_ES,
    /*-------------------------------- Public ---------------------------------------------*/
    'Public.Overview': "Genel Bakış",
    'Public.WelcometoROYALCANIN': "Royal Canin'e Hoş Geldiniz",
    'Public.storeportal': "Mağaza Girişi",
    'Public.Pleaseselectyourrole': "Lütfen rolünüzü seçin",
    'Public.RCStaff': "RC Personeli",
    'Public.Prescriber': "Hekim",
    'Public.R': "R",
    'Public.Storeportal': "Mağaza Girişi",
    'Public.LoginAccount': "Giriş Hesabı",
    'Public.RoyalCaninSAS2020': "Royal Canin SAS 2020",
    'Public.Pleaseinputyour': "Lütfen kullanıcı bilgilerinizi yazın",
    'Public.Login': "Oturum aç",
    'Public.UnderReview': "İnceleme altında",
    'Public.Yourapplication': "Başvurunuz ilgili hekime gönderildi. Hesabınızı inceledikten sonra sonucu size e-posta ile bildireceğiz.",
    'Public.Return': "Geri",
    'Public.Password': "Şifre",
    'Public.Thisserviceis': "Bu hizmet sadece müşterilerimiz içindir.",
    'Public.YourclientID': "Müşteri ID'niz, Royal Canin faturanızda belirtilmiştir. Bu bir e-posta adresi veya bir müşteri numarası olabilir.",
    'Public.Proceed': "İlerle",
    'Public.Passwordcannotbeempty': "Şifre boş bırakılamaz",
    'Public.save': "Kaydet",
    'Public.cancel': "İptal",
    'Public.more': "Daha Fazla",
    'Public.all': "Tümü",
    'Public.Search': "Ara",
    "Public.GetDataFailed": 'eri Alma Başarısız',

    /*-----------------------------  Home -----------------------------------------------*/
    'Home.Overview': 'Genel Bakış',
    'Home.Revenue': 'Gelir',
    'Home.Averagebasket': 'Ortalama sepet tutarı',
    'Home.Conversion': 'Dönüşüm',
    'Home.Traffic': 'Trafik',
    'Home.Trafficrate': 'Trafik Oranı',
    'Home.Conversionfunnel': 'Dönüşüm Hunisi',
    'Home.Conversionrate': 'Dönüşüm Oranı',
    'Home.more': 'Daha Fazla',
    'Home.Pageview': 'Sayfa Görünümü',
    'Home.VETtraffic': 'VET Trafiği',
    'Home.VETtrafficrate': 'VET Trafik Oranı',
    'Home.OrderNumber': 'Sipariş Numarası',
    'Home.Salesvolume': 'Satış Hacmi',
    'Home.Unitssold': 'Satılan Birimler',
    'Home.Retentionrate': 'Müşteri Koruma Oranı',
    'Home.Consumer': 'Tüketici',
    'Home.Activeconsumers': 'Aktif Tüketiciler',
    'Home.Activeconsumerrate': 'Aktif Tüketici Oranı',
    'Home.Totalconsumers': 'Toplam Tüketici',
    'Home.Subscription': 'Abonelik',
    'Home.Prescriber': 'Hekim',
    'Home.Activeprescriberrates': 'Aktif Hekim Oranı',
    'Home.Activeprescribers': 'Aktif Hekimler',
    'Home.PrescriberrewardTop3': 'Hekim Ödülleri Top 3',
    'Home.Bestseller': 'En Çok Satanlar',
    'Home.TrafficTrend': 'Trafik Trendleri',
    'Home.PrescribersTrend': 'Hekim Trendleri',
    'Home.TransactionTrend': 'İşlem trendleri',
    'Home.Prescriberreward': 'Hekim Ödülleri',
    'Home.Activerate': 'Aktif Oran',
    'Home.Transaction': 'İşlem',
    /* -------- 已翻译 V1.0---------------*/

    /*-----------------------------  Order  --------------------------------------------*/
    'Order.AuditSetting': 'Denetim Ayarları',
    'Order.AutoAudit': 'Otomatik Denetim',
    'Order.ManualAudit': 'Manuel Denetim',
    'Order.OperateSuccessfully': 'Başarılı',
    'Order.Category': 'Kategori',
    'Order.ParentCategory': 'Üst kategori',
    'Order.NeedAudit': 'Denetime ihtiyacınız var',
    'Order.NeedPrescriber': 'Hekime ihtiyacınız var',
    'Order.AuditMethod': 'Denetim Metodu',
    'Order.Edit': 'Düzenle',
    'Order.SelectRequiresPrescriber': 'Lütfen ürün kategorisinin hekim gerektirip gerektirmediğini seçin.',
    'Order.Close': 'Kapat',
    'Order.PetInformationAs': 'Hayvan Bilgileri',
    'Order.selectBeReviewed': 'Lütfen incelenecek ürün kategorisini seçin',
    'Order.SignedCategory': 'Kayıtlı Kategori',
    'Order.categoriesHave': "Maksimum kategori sayısı 200'dür.",
    'Order.PetInformation': 'Hayvan Bilgileri',
    'Order.Order': 'Sipariş Ayarları',
    'Order.OperationTips': 'İpuçları',
    'Order.PaymentBeforeDelivery': 'Teslimat Öncesi Ödeme',
    'Order.OnlinePayment': 'Çevrimiçi Ödeme',
    'Order.SaveSuccessful': 'Kaydedildi',
    'Order.Ordersution': '1. Sipariş ayarları, sipariş iade işleminin temel süreciyle ilişkilidir. Lütfen işlemleri dikkatle uygulayın, "Kaydet" butonuna bastıktan sonra seçilen ayarlar devreye girecektir.',
    'Order.IfTheCustomer': '2. Müşterinin vadesi geçmiş ve işlenmemiş siparişleri varsa, makbuz otomatik olarak onaylanacaktır.',
    'Order.IfTheCmpleted': '3. Tamamlanan sipariş belirlenen süreyi aşarsa, müşteri iade başvurusunda bulunamaz.',
    'Order.ThePending': '4. Satıcı tarafından işleme alınmamış bekleyen iade siparişleri otomatik olarak onaylanacaktır.',
    'Order.TheMerchant': '5. Satıcı tarafından işlenmemiş "bekleyen iadelerin" makbuzları otomatik olarak onaylanacaktır.',
    'Order.Select': '"Teslimat Öncesi Ödeme" seçeneğinde müşteri, ürün gönderilmeden ödemeyi yapmalıdır. "Sınırsız" seçeneğinde ise böyle bir gereklilik yoktur.',
    'Order.PaymentCategory': 'Ödeme Kategorisi',
    'Order.Cash': 'Nakit',
    'Order.OrderExpirationTime': 'Siparişin Geçerlilik Süresi',
    'Order.AfterHours': 'Müşteri, ödemeyi belirlenen süre içinde gerçekleştirmezse, sipariş otomatik olarak iptal edilecektir.',
    'Order.Automatically': 'Siparişin otomatik onaylanması',
    'Order.AfterDays': 'Müşterinin gecikmiş ve işlenmemiş bekleyen siparişleri, birkaç gün sonra otomatik olarak onaylanacaktır.',
    'Order.CompletedOrders': 'Tamamlanan siparişler için iade başvurusunda bulunulabilir.',
    'Order.WithinDays': 'Müşterilerin birkaç gün içinde iadeye başvurma hakkı vardır, ayrıca henüz gönderilmemiş siparişler için de her an iadeye başvurulabilir.',
    'Order.Automatic': 'Bekleyen iadelerin otomatik incelemesi',
    'Order.AfterDaysMerchant': 'Satıcının gecikmiş ve bekleyen iade siparişleri birkaç gün sonra otomatik olarak onaylanacaktır.',
    'Order.AutomaticConfirmation': 'İadelerin otomatik onaylanması',
    'Order.AfterDaysAutomatically': 'Satıcı tarafından zamanında işleme alınmayan bekleyen iadeler birkaç gün sonra otomatik olarak onaylanacaktır. Hızlı(Ekspres) olmayan teslimatlarda inceleme tamamlandıktan sonra iade süreci başlatılacaktır.',
    'Order.AfterHoursCustomer': 'Müşteri, ödemeyi belirlenen süre içinde gerçekleştirmezse, sipariş otomatik olarak iptal edilecektir.',
    'Order.AutomaticallyConfirm': 'Siparişin otomatik onaylanması',
    'Order.AfterDaysCustomer': 'Müşterinin gecikmiş ve işlenmemiş bekleyen siparişleri, birkaç gün sonra otomatik olarak onaylanacaktır.',
    'Order.CompletedOrdersAllowed': 'Tamamlanan siparişler için iade başvurusunda bulunulabilir.',
    'Order.WithinDaysCustomers': 'Müşterilerin birkaç gün içinde iadeye başvurma hakkı vardır, ayrıca henüz gönderilmemiş siparişler için de her an iadeye başvurulabilir.',
    'Order.AutomaticReview': 'Bekleyen iadelerin otomatik incelemesi',
    'Order.AfterDaysTheMerchant': 'Satıcının gecikmiş ve bekleyen iade siparişleri birkaç gün sonra otomatik olarak onaylanacaktır.',
    'Order.AutomaticReceipt': 'İadelerin otomatik onaylanması',
    'Order.AfterTheMerchant': 'Satıcı tarafından zamanında işleme alınmayan bekleyen iadeler birkaç gün sonra otomatik olarak onaylanacaktır. Hızlı(Ekspres) olmayan teslimatlarda inceleme tamamlandıktan sonra iade süreci başlatılacaktır.',
    'Order.Unlimited': 'Sınırsız',
    'Order.HoursCustomer': 'Müşteri, ödemeyi belirlenen süre içinde gerçekleştirmezse, sipariş otomatik olarak iptal edilecektir.',
    'Order.CustomerOverdue': 'Müşterinin gecikmiş ve işlenmemiş bekleyen siparişleri, birkaç gün sonra otomatik olarak onaylanacaktır.',
    'Order.CompletedAllowed': 'Tamamlanan siparişler için iade başvurusunda bulunulabilir.',
    'Order.AllowedToInitiate': 'Müşterilerin birkaç gün içinde iadeye başvurma hakkı vardır, ayrıca henüz gönderilmemiş siparişler için de her an iadeye başvurulabilir.',
    'Order.AfterOverdueAndPending': 'Satıcının gecikmiş ve bekleyen iade siparişleri birkaç gün sonra otomatik olarak onaylanacaktır.',
    'Order.ConfirmationOfReceipt': 'İadelerin otomatik onaylanması',
    'Order.TheMerchantAutomatically': 'Satıcı tarafından zamanında işleme alınmayan bekleyen iadeler birkaç gün sonra otomatik olarak onaylanacaktır. Hızlı(Ekspres) olmayan teslimatlarda inceleme tamamlandıktan sonra iade süreci başlatılacaktır.',
    'Order.save': 'Kaydet',
    'Order.all': 'Tümü',
    'Order.pendingReview': 'İnceleme bekliyor',
    'Order.toBeFilledOutLogisticsInformation': 'Lojistik bilgilerinin doldurulması gerekiyor',
    'Order.waitingForTheMerchantToReceiveTheGoods': 'Satıcının ürünleri alması bekleniyor',
    'Order.pendingRefund': 'Bekleyen İadeler',
    'Order.rejected': 'Reddedildi',
    'Order.refusedToRefund': 'İade başvurusu reddedildi',
    'Order.refundFailed': 'İade başarısız oldu',
    'Order.initiateApplication': 'Satış sonrası hizmet desteği alın',
    'Order.search': 'Ara',
    'Order.consumerName': 'Tüketici Adı',
    'Order.consumerAccount': 'Tüketici Hesabı',
    'Order.recipient': 'Alıcı',
    'Order.recipientPhone': 'Alıcı Telefonu',
    'Order.productName': 'Ürün Adı',
    'Order.skuCode': 'SKU kodu',
    'Order.commodity': 'Ürünler',
    'Order.amount': 'Miktar',
    'Order.quantity': 'Miktar',
    'Order.noData': 'Veri yok',
    'Order.Application': 'Uygulama',
    'Order.ignore': '//@ts-ignore',
    'Order.total': 'Toplam',
    'Order.ClinicsCRM': 'Klinik CRM ID',
    'Order.ClinicsName': 'Klinik Adı',
    'Order.ClinicsRegion': 'Bölge',
    'Order.PrescriptionId': 'Reçete ID',
    'Order.OrderTime': 'Sipariş Zamanı',
    'Order.OrderNumber': 'Sipariş Numarası',
    'Order.ProductId': 'Ürün ID',
    'Order.UnitPrice': 'Birim Fiyat',
    'Order.Qty': 'Adt',
    'Order.OrderProductAmount': 'Ürün Miktarı',
    'Order.TotalOrderAmount': 'Toplam Sipariş Miktarı',
    'Order.OrderStatus': 'Sipariş Durumu',
    'Order.view': 'Görünüm',
    'Order.Confirm': 'Faturalandırmayı onaylıyor musunuz？',
    'Order.Cancel': 'Fatura kaydını iptal etmek istiyor musunuz？',
    'Order.btnConfirm': 'Onayla',
    'Order.btnCancel': 'İptal',
    'Order.order': 'Sipariş',
    'Order.Orderlist': 'Sipariş Listesi',
    'Order.Ordernumber': 'Sipariş Numarası',
    'Order.Subscriptionumber': 'Abonelik Numarası',
    'Order.Petownername': 'Evcil Hayvan Sahibinin Adı',
    'Order.Petowneraccount': 'Evcil Hayvan Sahibi Hesabı',
    'Order.Productname': 'Ürün Adı',
    'Order.SKUcode': 'SKU kodu',
    'Order.Recipient': 'Alıcı',
    'Order.Recipientphone': 'Alıcı Telefonu',
    'Order.Auditorname': 'Denetçi Adı',
    'Order.Auditorid': "Denetçi ID'si",
    'Order.Paymentstatus': 'Ödeme Durumu',
    'Order.Shippingstatus': 'Nakliye Durumu',
    'Order.OrderCategory': 'Sipariş Kategorisi',
    'Order.Startdate': 'Başlangıç Tarihi',
    'Order.Enddate': 'Öneren Kişinin Adı',
    'Order.Recommendername': "Öneren Kişinin ID'si",
    'Order.Recommenderid': 'Lütfen bir dışa aktarma metodu seçin',
    'Order.Bulkoperations': 'Seçili siparişleri dışa aktar',
    'Order.BatchExport': 'Filtrelenmiş siparişleri dışa aktar',
    'Order.Exportfilteredorders': 'Dışa aktarma Ayrıntıları',
    'Order.Exportselectedorders': 'Dışa aktar',
    'Order.Pendingreview': 'Bekleyen İnceleme',
    'Order.Tobedelivered': 'Henüz teslim edilmedi',
    'Order.Tobereceived': 'Henüz teslim alınmadı',
    'Order.Completed': 'Tamamlandı',
    'Order.Outofdate': 'Yürürlükte değil',
    'Order.Product': 'Ürünler',
    'Order.Amount': 'Miktar',
    'Order.Quantity': 'Adet',
    'Order.Seedetails': 'Detayları gör',
    'Order.DeliveryRecord': 'Teslim Kayıtları',
    'Order.PaymentRecords': 'Ödeme Kayıtları',
    'Order.Ordertime': 'Sipariş Zamanı',
    'Order.Consumertype': 'Tüketici Tipi',
    'Order.Phonenumber': 'Telefon Numarası',
    'Order.ProductName': 'Ürün Adı',
    'Order.Weight': 'Ağırlık',
    'Order.Price': 'Fiyat',
    'Order.Subtotal': 'Ara Toplam',
    'Order.Productamount': 'Ürün Miktarı',
    'Order.Shippingfees': 'Nakliye Ücreti',
    'Order.Total': 'Toplam',
    'Order.DeliveryCountry': 'Teslimat Ülkesi',
    'Order.DeliveryInvoiceaddress1': 'Teslimat Faturası Adresi 1',
    'Order.DeliveryCity': 'Teslimat Şehri',
    'Order.DeliveryInvoiceaddress2': 'Teslimat Faturası Adresi 2',
    'Order.Deliveryaddress1': 'Teslimat Adresi 1',
    'Order.Deliveryaddress2': 'Teslimat Adresi 2',
    'Order.Postalcode': 'Posta Kodu',
    'Order.Reference': 'Referans',
    'Order.Deliverycomment': 'Teslimat Yorumu',
    'Order.Operationlog': 'Operasyon Günlüğü',
    'Order.OperatorType': 'Operatör Tipi',
    'Order.Operator': 'Operatör',
    'Order.Time': 'Zaman',
    'Order.OperationCategory': 'Operasyon Kategorisi',
    'Order.OperationLog': 'Operasyon Günlüğü',
    'Order.No.': 'No.',
    'Order.Shipped': 'Ürün yola çıktı',
    'Order.ThisShipment': 'Bu Sevkiyat',
    'Order.Amountreceivable': 'Alacak Miktarı',
    'Order.CollectionSerialNumber': 'Tahsilat Numarası',
    'Order.CollectionTime': 'Tahsilat Zamanı',
    'Order.AmountReceived': 'Alınan Miktar',
    'Order.AccountsReceivable': 'Alacak Hesapları',
    'Order.Accessories': 'Aksesuarlar',
    'Order.Status': 'Durum',
    'Order.Remarks': 'Notlar',
    'Order.Operatio': 'Operasyon',
    'Order.PaymentId': 'Ödeme ID',
    'Order.PaymentTime': 'Ödeme Zamanı',
    'Order.Name': 'Adı Soyadı',
    'Order.Email': 'E-posta Adresi',
    'Order.Cardnumber': 'Kart Numarası',
    'Order.Paymentmethod': 'Ödeme Yöntemi',
    'Order.Comment': 'Yorum ',
    'Order.Pleaseinputcomment': 'Lütfen yorum girin',
    'Order.AddComment': 'Yorum ekle',
    'Order.Delete': 'Sil',
    'Order.Pleaseselecttheorder': 'Lütfen sipariş seçin',
    'Order.Audit': 'Denetim',
    'Order.Confirmtoreview?': 'Seçili siparişi incelemeyi onaylıyor musunuz?',
    'Order.Batchreview': 'Toplu İnceleme',
    'Order.Batchexport': 'Dışa Aktar',
    'Order.Consumername': 'Tüketici Adı',
    'Order.Consumeraccount': 'Tüketici Hesabı',
    'Order.Unpaid': 'Ödenmedi',
    'Order.Paid': 'Ödendi',
    'Order.All': 'Tümü',
    'Order.Tobeconfirmed': 'Onay bekleniyor',
    'Order.Paying': 'Ödeme gerçekleşiyor',
    'Order.notshipped': 'Ürün henüz yola çıkmadı',
    'Order.Partialshipment': 'Kısmi Sevkiyat',
    'Order.Allshipments': 'Tüm Sevkiyatlar',
    'Order.Singlepurchase': 'Tek Satın Alım',
    'Order.1stautoshiporder': '1. Otomatik Sipariş',
    'Order.Recurrentorders of autoship': 'Tekrarlayan Otomatik Siparişler',
    'Order.Export': 'Bitiş Tarihi',
    'Order.Search': 'Ara',
    'Order.Pleaseselectanexportmethod': 'Operasyon Hacmi',
    'Order.Orderstatus': 'Sipariş Durumu',
    'Order.Doyouconfirmthat': 'Siparişin kabul edildiğini onaylıyor musunuz?',
    'Order.Confirmthatallproducts': 'Tüm ürünlerin teslim alındığını onaylıyor musunuz?',
    'Order.Invalid': 'Geçersiz',
    'Order.Unknown': 'Bilinmeyen',
    'Order.Refund': 'İade',
    'Order.Tobeformed': 'Bekleniyor',
    'Order.RejectionReasonTip': 'Lütfen reddetme nedenini yazın',
    'Order.OncerejectedTip': 'Eğer başvuru reddedilirse, bu siparişin ödemesini tüketiciye iade edeceğiz.',
    'Order.OrderDetails': 'Sipariş Detayları',
    'Order.Promotionamount': 'Promosyon Miktarı',
    'Order.Tax': 'Vergi',
    'Order.Save': 'Kaydet',
    'Order.specialNeeds': 'Özel İhtiyaçlar',
    'Order.Re-review': 'Tekrar İnceleme',
    'Order.ConfirmReceipt': 'Makbuzu onayla',
    'Order.Confirmtoreturntheselected': '"Yeniden Onay" için seçilen siparişi iade etmeyi onaylıyor musunuz?',
    'Order.Confirmreceiptofallitems': 'Tüm öğelerin alındığını onaylıyor musunuz?',
    'Order.Valetorder': 'Vale Siparişi',
    'Order.Fighttogether': 'Birlikte mücadele edin!',
    'Order.ConfirmAudit': 'Seçili siparişi incelemeyi onaylıyor musunuz?',
    'Order.Modify': 'Değiştir',
    'Order.Consumer': 'Tüketici',
    'Order.Promotion': 'Promosyon',
    'Order.Back': 'Geri',
    'Order.Whethertoinvalidate': 'Bu teslimat kaydını iptal ediyor musunuz?',
    'Order.Turndown': 'Geri çevir',
    'Order.Items': 'Öğeler',
    'Order.Piece': 'Parça',
    'Order.Review': 'İnceleme',
    'Order.ConfirmReview': 'Yeniden değerlendirme için seçilen siparişi iade etmek istediğinize emin misiniz?',
    'Order.Trackdelivery': 'Teslimat Takibi',
    'Order.Refresh': 'Yenile',
    'Order.PetOwner': 'Evcil hayvan sahibi',
    'Order.orderList': 'Sipariş Listesi',
    'Order.subscriptioNumber': 'Abonelik Numarası',
    'Order.shippingStatus': 'Nakliye Durumu',
    'Order.paymentStatus': 'Ödeme Durumu',
    'Order.orderStatus': 'Sipariş Durumu',
    'Order.orderSource': 'Sipariş Kaynağı',
    'Order.startDate': 'Başlangıç Tarihi',
    'Order.endDate': 'Bitiş Tarihi',
    'Order.bulkOperations': 'Operasyon Hacmi',
    'Order.toBeFormed': 'Bekleniyor',
    'Order.notShipped': 'Ürün henüz yola çıkmadı',
    'Order.toBeDelivered': 'Henüz teslim edilmedi',
    'Order.toBeReceived': 'Henüz teslim alınmadı',
    'Order.paid': 'Ödendi',
    'Order.unpaid': 'Ödenmedi',
    'Order.toBeConfirmed': 'Onay bekleniyor',
    'Order.received': 'Alındı',
    'Order.confirmReceipt': 'Makbuzu onayla',
    'Order.completed': 'Tamamlandı',
    'Order.outOfDate': 'Yürürlükte değil',
    'Order.ship': 'Yolla',
    'Order.allShipments': 'Tüm Sevkiyatlar',
    'Order.partialShipment': 'Kısmi Sevkiyat',
    'Order.invalid': 'Geçersiz',
    'Order.unknown': 'Bilinmeyen',
    'Order.seeDetails': 'Detayları gör',
    'Order.PCOrder': 'PC Siparişi',
    'Order.H5Order': 'H5 Siparişi',
    'Order.AppOrder': 'APP Siparişi',
    'Order.miniProgramOrder': 'Mini Program Siparişi',
    'Order.rejectionReasonTip': 'Lütfen reddetme nedenini yazın',
    'Order.100charactersLimitTip': 'Maksimum 100 karakter girebilirsiniz',
    'Order.valetOrder': 'Vale Siparişi',
    'Order.fightTogether': 'Birlikte mücadele edin!',
    'Order.audit': 'Denetim',
    'Order.turnDown': 'Geri çevir',
    'Order.review': 'İnceleme',
    'Order.confirmReceivedAllProducts': 'Tüm ürünlerin teslim alındığını onaylıyor musunuz?',
    'Order.confirmReview': 'Yeniden değerlendirme için seçilen siparişi iade etmek istediğinize emin misiniz?',
    'Order.confirmAudit': 'Seçili siparişi incelemeyi onaylıyor musunuz?',
    'Order.exportFilterOrder': 'Lütfen sipariş seçin',
    'Order.exportSelectedOrder': 'Toplu İnceleme',
    'Order.pleaseSelectOrderToOperate': 'Siparişi düzenle',
    'Order.batchReview': 'Bir üye seçmelisiniz',
    'Order.batchExport': 'Adres yok, lütfen geçici bir adres girin',
    'Order.editOrder': 'Bir gönderim adresi seçmelisiniz',
    'Order.mustSelectAMember': 'Lütfen İl, İlçe ve Mahalle seçin',
    'Order.noAddressAvailable': 'Lütfen detaylı adresi girin',
    'Order.mustChooseAShippingAddress': 'Adres uzunluğu 5-60 karakter arasında olmalıdır',
    'Order.pleaseSelectProvinceOrCityOrDistrict': 'Lütfen alıcı bilgisini girin',
    'Order.inputDetailAddressTip1': "Desteklenen resim formatları: jpg, jpeg, png, gif. Dosya boyutu en fazla 5 MB olup, maksimum yükleme sayısı 10'dur.",
    'Order.inputDetailAddressTip2': "Resim boyutu 5 MB'yi geçemez",
    'Order.inputReceiverTip': 'Sipariş Fiyatı Değişikliği',
    'Order.uploadValidateTip': 'Teslimat Bilgisi',
    'Order.uploadValidateTip2': 'Alıcı',
    'Order.orderPriceChange': 'Telefon Numarası',
    'Order.deliveryInformation': 'Varsayılan Adres',
    'Order.receiver': 'Alan',
    'Order.phoneNumber': 'Detaylı Adres',
    'Order.defaultAddress': 'Telefon Numarası',
    'Order.area': 'Lütfen telefon numarasını girin',
    'Order.detailAddress': 'Lütfen doğru telefon numarasını girin',
    'Order.phoneNumber2': 'Teslimat Yöntemi',
    'Order.inputPhoneNumberTip': 'Diğer Bilgiler',
    'Order.inputPhoneNumberTip2': 'Hızlı Teslimat',
    'Order.deliveryMethod': 'Ödeme Yöntemi',
    'Order.extraInformation': 'Çevrimiçi Ödeme',
    'Order.expressDelivery': 'Çevrimdışı Ödeme',
    'Order.paymentMethod': 'Fatura Bilgisi',
    'Order.onlinePayment': 'Fatura gerekmez',
    'Order.offlinePayment': 'Bireysel',
    'Order.invoiceInformation': 'Şirket',
    'Order.noInvoiceRequired': 'Lütfen fatura kalemini seçin',
    'Order.personal': 'Fatura kalemi seçilmeli',
    'Order.company': 'Fatura Başlığı',
    'Order.pleaseSelectInvoiceItem': 'Fatura başlığı girilmelidir',
    'Order.mustSelectInvoiceItem': 'Fatura başlığı en az 1 karakter olmalıdır',
    'Order.invoiceHeader': 'Fatura başlığı maksimum 50 karakter olabilir',
    'Order.mustFillInTheInvoiceHeader': 'Vergi Kimlik Numarası',
    'Order.invoiceHeaderValidateTip1': 'Lütfen doğru vergi kimlik numarasını girin (15-20 karakter)',
    'Order.invoiceHeaderValidateTip2': 'Bilgileri yanlış girmeniz durumunda vergi sertifikası geçersiz olacak ve masraflarınız karşılanmayacaktır.',
    'Order.taxpayerIdentificationNumber': 'Şirketin Tam Adı',
    'Order.taxpayerIdentificationNumberValidateTip': 'Şirket Vergi Kimlik Numarası',
    'Order.taxpayerIdentificationNumberValidateTip2': 'Şirket Telefonu',
    'Order.companyFullName': 'Banka Hesap Numarası',
    'Order.companyTaxpayerIdentificationNumber': 'Banka',
    'Order.companyPhone': 'Ayrı fatura bilgisi kullanın',
    'Order.basicBankAccountNumber': 'Adres',
    'Order.bank': 'Notları doldurun',
    'Order.useSeparateInvoiceReceiptInformation': 'Maksimum 100 karakter girebilirsiniz',
    'Order.address': 'SPU kodu',
    'Order.fillInTheRemarks': 'Marka',
    'Order.enterUpTo100Characters': 'Kategori',
    'Order.spuCode': 'Lütfen üye seçin',
    'Order.brand': 'Ürün ekle',
    'Order.catogery': 'Bir ürün seçmelisiniz',
    'Order.Pleaseselectmember': 'Seri Numarası',
    'Order.addProduct': 'Eşantiyon',
    'Order.Mustselectaproduct': 'Üyelik Fiyatı',
    'Order.serialNumber': 'Satın alma miktarı giriniz!',
    'Order.giveaway': 'Satın Alma Hacmi',
    'Order.memberPrice': 'Satın alma hacmi, kalan envanterden fazla olamaz.',
    'Order.Purchasequantity': 'Satın alma hacmi, envanterden fazla olamaz.',
    'Order.Purchasevolume': 'Satın alma hacmi, sınırlı emir miktarından fazla olamaz.',
    'Order.Thepurchasevolume': 'Satın alma hacmi, minimum miktardan az olamaz.',
    'Order.Purchasevolumecannot': 'Stok',
    'Order.Thepurchasevolumecannot': 'Minimum Sipariş Miktarı',
    'Order.Thepurchasevolumecannotbeless ': 'Lütfen miktarı girin',
    'Order.stock ': 'Lütfen doğru miktarı girin',
    'Order.Minimumorderquantity ': 'Nakliye Ücreti',
    'Order.Pleaseentertheamount': 'Çıkarılacak toplam tutar',
    'Order.Pleaseenterthecorrectamount': 'Toplam indirim tutarı',
    'Order.shippingFees': 'Kupon',
    'Order.fullReductionAmount': 'Puan Kesintisi',
    'Order.fullDiscountAmount': 'Ödenecek Toplam',
    'Order.coupon': 'Maksimum 50 türde ürün mevcuttur',
    'Order.pointsDeduction': 'Ürün Seç',
    'Order.totalPayable': 'Otomatik Denetim',
    'Order.Nomorethan50': 'Manuel Denetim',
    'Order.Selectproduct': 'Başarılı',
    /* -------- 已翻译 V1.0---------------*/

    /*-----------------------------  Task  ----------------------------------------------*/
    'task.CardView': 'Kart Görünümü',
    'task.ListView': 'Liste görünümü',
    'task.MyTasks': 'Görevlerim',
    'task.AllTasks': 'Tüm görevler',
    'task.ToDo': 'Yapılacaklar',
    'task.On-going': 'Devam eden',
    'task.Completed': 'Tamamlandı',
    'task.Cancelled': 'İptal edildi',
    'task.NoAssistantName': 'Asistan Adı Yok',
    'task.NoDueTime': 'Bitiş Zamanı Yok',
    'task.TaskName': 'Görev adı',
    'task.GoldenMoment': 'Altın An',
    'task.TaskStatus': 'Görev Durumu',
    'task.Priority': 'Öncelik',
    'task.Email': 'E-posta',
    'task.PetAssistant': 'Evcil Hayvan Asistanı',
    'task.PetAssistantName': 'Evcil Hayvan Asistanı Adı',
    'task.PetOwnerName': 'Evcil Hayvan Sahibi Adı',
    'task.PetOwner': 'Evcil Hayvan sahibi',
    'task.DueDate': 'Bitiş tarihi',
    'task.TaskCreation': 'Görev Oluşturma',
    'task.Inputtasknametocreateanewtask': 'Yeni bir görev oluşturmak için görev adını girin',
    'task.Assignedto': 'a atandı',
    'task.StartTime': 'Başlangıç saati',
    'task.DueTime': 'Bitiş Zamanı',
    'task.TaskCreationTime': 'Görev Oluşturma Zamanı',
    'task.aftertaskstarted': 'görev başladıktan sonra',
    'task.ReminderTime': 'Hatırlatma Zamanı',
    'task.PetOwnerPlan': 'İletişim Planı',
    'task.DescriptionTask': 'Açıklama Görevi',
    'task.Description': 'Açıklama',
    'task.ActionType': 'Eylem Türü',
    'task.AssociatedPetOwner': 'İlişkili Evcil Hayvan Sahibi',
    'task.AssociatedPet': 'ilişkili Evcil Hayvan',
    'task.AssociatedOrder': 'İlişkili Sipariş',
    'task.TaskDetails': 'Görev Ayrıntıları',
    'task.Pleaseinputname': 'Lütfen isim girin',
    'task.Pleaseinputemail': 'Lütfen e-posta girin',
    'task.Pleaseinputemailorname': 'Please input email or name',
    'task.Pleaseinputordercode': 'Lütfen sipariş kodunu girin',
    'task.Pleaseselectstarttime': 'Please select start time',
    'task.Pleaseselectduetime': 'Please select due time',
    'task.Reminderbeforeduetime': 'Reminder before due time',
    'task.Pleaseinputpetowneraccountorname': 'Please input pet owner account or name',
    'task.Tobeadd': 'Eklenecek',
    'task.AllActivity': 'Tüm etkinlikler',
    'task.AuditLog': 'Denetim Günlüğü',
    'task.Comments': 'Yorumlar',
    'task.More': 'Daha',
    'task.Less': 'Az',
    'task.CannotCompletedwithoutoutcome': 'Sonuç olmadan tamamlanamaz',
    'task.Pleasechangethestatustonotcompleted': 'Lütfen durumu tamamlanmadı olarak değiştirin',
    'task.PleaseselectGoldenMoment': "Lütfen Altın An'ı seçin",
    'task.PleaseselectPetOwnerPlan': 'Lütfen Evcil Hayvan Sahibi Planını Seçin',
    'task.High': 'Yüksek',
    'task.Feedback': 'Geri bildirim',
    'task.AddFeedback': 'Geri Bildirim Ekle',
    'task.BasicInformation': 'Temel Bilgiler',
    'task.Save': 'Kayıt etmek',
    'task.Minutes': 'Dakika',
    'task.Hours': 'Saat',
    'task.Days': 'Gün',
    'task.Weeks': 'Hafta',
    'task.Months': 'Ay',
    'task.Low': 'Düşük',
    'task.Medium': 'Orta',
    'task.Call': 'Aramak',
    'task.N/A': 'N/A',
    'task.Cancel': 'İptal Et',
    'task.Type': 'Tip',
    'task.Status': 'Rezervasyon durumu',
    'task.StartDate': 'Başlangıç tarihi',
    'task.EndDate': 'Bitiş tarihi',
    'task.Subscription': 'Abonelik',
    'task.TaskBoard': 'Görev Panosu',
    'task.Viewalltask': 'Tüm görevleri görüntüle',
    'task.AdvanceSearch': 'Detaylı Arama',
    'task.DueStarttime': 'Başlama Zamanı',
    'task.DueEndtime': 'Bitirme Tarihi',
    'task.AddNewTask': 'Yeni Görev Ekle',
    'task.AssociateSubscription': 'İlgili Abonelik',
    'task.Taskcreation': 'Task creation',
    'task.Taskedition': 'Görev düzenleme',
    'task.Back': 'Geri',
    'task.Activity': 'Etkinlik',
    'task.Number': 'Numara',
    'task.Productname': 'Ürün adı',
    'task.PetOwnerOverview': 'Evcil Hayvan Sahibine Genel Bakış',
    'task.1stpurchasefororderconfirmation(Club)': 'Sipariş onayı için ilk satın alma (Kulüp)',
    'task.1stmonthofSubscription': 'Üyeliğin 1. Ayı',
    'task.Half-yearsubscription': 'Yarım yıllık abonelik',
    'task.1-yearsubscription': '1 yıllık abonelik',
    'task.After1stdelivery': '1. gönderi sonrası',
    'task.After4thdelivery': '4. gönderi sonrası',
    'task.SubscriptionprogramcancelationbyPO': 'PO tarafından abonelik programı iptali',
    'task.Foodtransition(newlife-stage)': 'Yiyecek geçişi (yeni yaşam aşaması)',
    'task.3daysbeforenextrefillorder': 'Bir sonraki gönderiden 3 gün önce',
    'task.By': 'Tarafından',
    /*-----------------------------  Subscription  ---------------------------------------*/

    'Subscription.SubscriptionList': 'Abone Listesi',
    'Subscription.searchForm.SubscriptionNumber': 'Abone Numarası',
    'Subscription.searchForm.ConsumerName': 'Tüketici Adı',
    'Subscription.searchForm.ProductName': 'Ürün Adı',
    'Subscription.searchForm.Receiver': 'Alıcı',
    'Subscription.searchForm.AuditorName': 'Denetçi Adı',
    'Subscription.subscriptionOption.SubscriptionNumber': 'Üyelik Numarası',
    'Subscription.subscriptionOption.OrderNumber': 'Sipariş Numarası',
    'Subscription.consumerOption.ConsumerName': 'Tüketici Adı',
    'Subscription.consumerOption.ConsumerAccount': 'Tüketici Hesabı',
    'Subscription.productOption.ProductName': 'Ürün Adı',
    'Subscription.productOption.SKUCode': 'SKU kodu',
    'Subscription.recipientOption.Receiver': 'Alıcı',
    'Subscription.recipientOption.ReceiverPhone': 'Alıcının Telefonu',
    'Subscription.prescriberOption.AuditorName': 'Denetçi Adı',
    'Subscription.prescriberOption.AuditorID': "Denetçi ID'si",
    'Subscription.TagManagementDetail': 'Etiket Yönetimi Detayları',
    'Subscription.OperationFailure': 'Operasyon hatası',
    'Subscription.OperationSuccessful': 'Operasyon başarılı',
    'Subscription.TagDescription': 'Etiket Açıklaması',
    'Subscription.CreatedOn': 'Şu tarihte oluşturuldu',
    'Subscription.LastModified': 'Son düzenleme',
    'Subscription.PetOwnerList': 'Evcil Hayvan Sahipleri (',
    'Subscription.Subscription': 'Abonelik Planı',
    'Subscription.PleaseInputKeyword': 'Lütfen anahtar kelime girin',
    'Subscription.batchExport': 'Toplu Dışa Aktarım',
    'Subscription.Frequency': 'Frekans',
    'Subscription.all': 'Tümü',
    'Subscription.Prescriber': 'Hekim',
    'Subscription.search': 'Ara',
    'Subscription.TabPane.all': 'Tümü',
    'Subscription.TabPane.Active': 'Aktif',
    'Subscription.TabPane.Inactive': 'Aktif değil',
    'Subscription.List.Product': 'Ürün',
    'Subscription.List.ProductName': 'Ürün Adı',
    'Subscription.List.SubscriptionStatus': 'Abonelik Durumu',
    'Subscription.List.consumerName': 'Tüketici Adı',
    'Subscription.List.operation': 'Operasyon',
    'Subscription.List.noData': 'Veri yok',
    'Subscription.order.notShipped': 'Ürün henüz yola çıkmadı',
    'Subscription.order.allShipments': 'Tüm Sevkiyatlar',
    'Subscription.order.partialShipment': 'Kısmi Sevkiyat',
    'Subscription.order.invalid': 'Geçersiz',
    'Subscription.order.unknown': 'Bilinmeyen',
    'Subscription.AreYouSureDelivery': 'Sonraki teslimatı atlamak istediğinize emin misiniz?',
    'Subscription.Subscriptions': 'Abonelik Detayları',
    'Subscription.SkipNextDelivery': 'Sonraki teslimatı atla',
    'Subscription.OperateSuccessfully': 'Başarılı',
    'Subscription.total': 'Toplam',
    'Subscription.piece': 'Parça',
    'Subscription.Details': 'Detaylar',
    'Subscription.Edit': 'Düzenle',
    'Subscription.CancelAll': 'Tümünü İptal Et',
    'Subscription.AreYouSureCancel': 'Aboneliği iptal etmek istediğinize emin misiniz?',
    'Subscription.List.Price': 'Fiyat',
    'Subscription.List.Quantity': 'Adet',
    'Subscription.List.DeliveryFrequency': 'Teslimat Frekansı',
    'Subscription.List.Total': 'Toplam',
    'Subscription.noStar.DeliveryDate': 'Teslimat Tarihi',
    'Subscription.noStar.Product': 'Ürün',
    'Subscription.completed.DeliveryDate': 'Teslimat Tarihi',
    'Subscription.completed.Product': 'Ürün',
    'Subscription.columnsCompleted.Product': 'Ürün',
    'Subscription.columnsCompleted.Quantity': 'Adet',
    'Subscription.columnsCompleted.EnjoyDiscount': 'İndiriminizi güle güle kullanın!',
    'Subscription.columnsCompleted.Amount': 'Miktar',
    'Subscription.columnsCompleted.ShipmentDate': 'Sevkiyat Tarihi',
    'Subscription.columnsCompleted.OrderStatus': 'Sipariş Durumu',
    'Subscription.columnsCompleted.Operation': 'Operasyon',
    'Subscription.operatorColumns.OperatorType': 'Operatör Tipi',
    'Subscription.operatorColumns.Operator': 'Operatör',
    'Subscription.operatorColumns.Time': 'Zaman',
    'Subscription.operatorColumns.OperationCategory': 'Operasyon Kategorisi',
    'Subscription.operatorColumns.OperationLog': 'Operasyon Günlüğü',
    'Subscription.noStart.Product': 'Ürün',
    'Subscription.noStart.Quantity': 'Adet',
    'Subscription.noStart.EnjoyDiscount': 'İndiriminizi güle güle kullanın!',
    'Subscription.noStart.Amount': 'Miktar',
    'Subscription.noStart.ShipmentDate': 'Sevkiyat Tarihi',
    'Subscription.AutoshipOrder': 'Otomatik Sipariş',
    'Subscription.NoStart': 'Başlangıç Yok',
    'Subscription.Completed': 'Tamamlandı',
    'Subscription.ColSpan.ubscriptionNumberS': 'Abone Numarası',
    'Subscription.ColSpan.SubscriptionDate': 'Abonelik Tarihi',
    'Subscription.ColSpan.AuditorID': "Denetçi ID'si",
    'Subscription.ColSpan.AuditorName': 'Denetçi Adı',
    'Subscription.ColSpan.ConsumerName': 'Tüketici Adı',
    'Subscription.ColSpan.ConsumerAccount': 'Tüketici Hesabı',
    'Subscription.ColSpan.ConsumerType': 'Tüketici Tipi',
    'Subscription.ColSpan.PhoneNumber': 'Telefon Numarası',
    'Subscription.ColSpan.Subtotal': 'Ara Toplam',
    'Subscription.ColSpan.Promotion': 'Promosyon',
    'Subscription.ColSpan.Shipping': 'Sevkiyat',
    'Subscription.ColSpan.Tax': 'Vergi',
    'Subscription.ColSpan.Total': 'Toplam',
    'Subscription.ColSpan.IVAInclude': 'IVA dahildir',
    'Subscription.ColSpan.DeliveryAddress': 'Teslimat Adresi',
    'Subscription.ColSpan.DeliveryAddress.Name': 'Adı Soyadı',
    'Subscription.ColSpan.DeliveryAddress.CityCountry': 'Şehir, Ülke',
    'Subscription.ColSpan.DeliveryAddress.Address1': 'Adres 1 ',
    'Subscription.ColSpan.DeliveryAddress.Address2': 'Adres 2',
    'Subscription.ColSpan.BillingAddress': 'Fatura Adresi',
    'Subscription.ColSpan.BillingAddress.Name': 'Adı Soyadı',
    'Subscription.ColSpan.BillingAddress.CityCountry': 'Şehir, Ülke',
    'Subscription.ColSpan.BillingAddress.Address1': 'Adres 1 ',
    'Subscription.ColSpan.BillingAddress.Address2': 'Adres 2',
    'Subscription.ColSpan.PaymentMethod': 'Ödeme Yöntemi',
    'Subscription.ColSpan.PaymentMethod.PaymentMethod': 'Ödeme Yöntemi',
    'Subscription.ColSpan.PaymentMethod.CardNumber': 'Kart Numarası',
    'Subscription.operationLog': 'Operasyon Günlüğü',
    'Subscription.back': 'Geri',
    'Subscription.Active': 'Aktif',
    'Subscription.Inactive': 'Aktif değil',
    'Subscription.RemindOfNewOrders': 'Yeni siparişleri hatırlat',
    'Subscription.Days1': 'Yeni siparişler oluşturulduktan birkaç gün sonra, hayvan sahiplerini haberdar etmek için bir e-posta gönderilir.',
    'Subscription.RemindOfCardExpiration': 'Kartın son kullanma tarihini hatırlat',
    'Subscription.Days2': 'Kartların son kullanma tarihi dolduğundan birka gün sonra, hatırlatma amaçlı bir e-posta gönderilir.',
    'Subscription.save': 'Kaydet',
    'Subscription.SubscriptionName': 'Üyelik Planı Adı',
    'Subscription.SubscriptionID': "Üyelik Planı ID'si",
    'Subscription.SubscriptionType': 'Üyelik Planı Türü',
    'Subscription.AddNewPlan': 'Yeni plan ekle',
    'Subscription.Table.SubscriptionID': "Üyelik Planı ID'si",
    'Subscription.Table.SubscriptionName': 'Üyelik Planı Adı',
    'Subscription.Table.SubscriptionType': 'Üyelik Planı Türü',
    'Subscription.Table.Quantity': 'Adet',
    'Subscription.Table.OfferTimePeriod': 'Teklif Süresi',
    'Subscription.Table.NumberofDelivery': 'Teslimat Sayısı',
    'Subscription.Table.Status': 'Durum',
    'Subscription.Table.Enable': 'İzin ver',
    'Subscription.Table.Operation': 'Operasyon',
    'Subscription.UpdateDataFailed': 'Veri Güncelleme Başarısız',
    'Subscription.Detail': 'Detaylar',
    'Subscription.GetPlanFailed': 'Plan Türü Listesi alınamadı!',
    'Subscription.Step1': '1. Aşama',
    'Subscription.BasicInformation': 'Temel Bilgiler',
    'Subscription.PlanType': 'Üyelik Planı Türü',
    'Subscription.PleaseInput': 'Lütfen Abonelik Planı Türü girin',
    'Subscription.PleasePlanName': 'Lütfen Abonelik Planı Adı girin',
    'Subscription.PleasePlanID': "Lütfen Abonelik Planı ID'si girin",
    'Subscription.Quantity': 'Adet',
    'Subscription.PleaseInputQuantity': 'Lütfen adet girin',
    'Subscription.LandingPage': 'Açılış Sayfası',
    'Subscription.PleaseInputLanding': 'Lütfen Açılış Sayfası girin',
    'Subscription.EnableLanding': 'Açılış sayfasını etkinleştirin',
    'Subscription.OfferTimePeriod': 'Teklif Süresi',
    'Subscription.PleaseSelectOffer': 'Lütfen Teklif Süresi seçin',
    'Subscription.PleaseSelectFrequency': 'Lütfen Frekans seçin',
    'Subscription.NumberOfDelivery': 'Teslimat Sayısı',
    'Subscription.PleaseInputNumber': 'Lütfen Teslimat Sayısı girin',
    'Subscription.Description': 'Açıklama',
    'Subscription.Step2': '2. Aşama',
    'Subscription.TargetProduct': 'Hedef Ürün',
    'Subscription.Image': 'Resim',
    'Subscription.SKU': 'SKU',
    'Subscription.ProductName': 'Ürün Adı',
    'Subscription.Specification': 'Şartname',
    'Subscription.ProductCategory': 'Ürün Kategorisi',
    'Subscription.Brand': 'Marka',
    'Subscription.Price': 'Fiyat',
    'Subscription.AddProduct': ' + ürün ekle',
    'Subscription.Step3': '3. Aşama',
    'Subscription.EntryCriteria': 'Kriter girin',
    'Subscription.ConsumersNeed': 'Tüketicilerin üyelik oturumu açmak için izne ihtiyacı var.',
    'Subscription.Consent': 'İzin ver',
    'Subscription.PleaseAddConsent': 'Lütfen İzin ekleyin',
    'Subscription.SubscriptionOtherPromotions': 'Üyelik planı diğer promosyonlarla birlikte uygulanabilir.',
    'Subscription.Step4': '4. Aşama',
    'Subscription.ExitRules': 'Çıkış Kuralları',
    'Subscription.CancellationPolicy': 'İptal Politikası',
    'Subscription.ConsumerCanChoose': 'Tüketici, planı iptal etmeyi seçebilir.',
    'Subscription.Yes': 'Evet',
    'Subscription.No': 'Hayır',
    'Subscription.ConsumerIsCharged': 'İptal durumunda tüketiciden bir ücret alınır.',
    'Subscription.TermsOfCancellation': 'İptal Koşulları',
    'Subscription.ConsumerIsChargedBefore': 'Tüketiciden önce bir ücret alınır.',
    'Subscription.ThisIsRequired': 'Bu alan gereklidir',
    'Subscription.refills': 'Takviyeler',
    'Subscription.TotalCancellationFee': 'Toplam İptal Ücreti',
    'Subscription.remainingNumberOfRefills': 'Kalan Takviye Sayısı',
    'Subscription.cancellationFeePerRefill': 'Takviye Başına Düşen İptal Ücreti',
    'Subscription.AdjustmentRules': 'Ayarlama Kuralları',
    'Subscription.ChangeDeliveryDate': 'Teslimat tarihini değiştir',
    'Subscription.After': 'Sonra',
    'Subscription.deliveryTimesDate': 'Tüketici bir sonraki teslimat tarihini değiştirebilir',
    'Subscription.SkipTheNextDelivery': 'Sonraki teslimatı atla',
    'Subscription.deliveryTimes': 'Tüketici bir sonraki teslimatı atlayabilir',
    'Subscription.Step5': '5. Aşama',
    'Subscription.Addproduct': 'Ürün ekle',
    'Subscription.PackageID': "Paket ID'si",
    'Subscription.Image1': 'Resim',
    'Subscription.ProductName1': 'Ürün Adı',
    'Subscription.Qty': 'Miktar',
    'Subscription.MarketPrice': 'Piyasa fiyatı',
    'Subscription.SettingPrice': 'Fiyat Belirleme',
    'Subscription.Operation': 'Operasyon',
    'Subscription.deleteThisProduct': 'Bu ürünü silmek istediğinize emin misiniz?',
    'Subscription.Delete': 'Sil',
    'Subscription.Confirm': 'Onayla',
    'Subscription.Cancel': 'İptal',
    'Subscription.ConsentTitle': 'İzin Başlığı',
    'Subscription.addConsent.ConsentId': "İzin ID'si",
    'Subscription.addConsent.ConsentCode': 'İzin Kodu',
    'Subscription.addConsent.ConsentType': 'İzin Türü',
    'Subscription.addConsent.Category': 'Kategori',
    'Subscription.addConsent.FieldType': 'Alan Türü',
    'Subscription.addConsent.AddConsents': 'İzin ekle',
    'Subscription.addConsent.Confirm': 'Onayla',
    'Subscription.addConsent.Cancel': 'İptal',
    'Subscription.addConsent.Prescriber': 'Hekim',
    'Subscription.addConsent.Consumer': 'Tüketici',
    'Subscription.addConsent.Optional': 'Opsiyonel',
    'Subscription.addConsent.Required': 'Zorunlu',
    'Subscription.addConsent.EmailIn': 'E-posta (In)',
    'Subscription.addConsent.EmailOut': 'E-posta (Out)',
    'Subscription.addConsent.ConsentTitle': 'İzin Başlığı',
    'Subscription.addConsent.search': 'Ara',
    'Subscription.addProduct.Image': 'Resim',
    'Subscription.addProduct.SKU': 'SKU',
    'Subscription.addProduct.ProductName': 'Ürün Adı',
    'Subscription.addProduct.Specification': 'Şartname',
    'Subscription.addProduct.ProductCategory': 'Ürün Kategorisi',
    'Subscription.addProduct.Brand': 'Marka',
    'Subscription.addProduct.Price': 'Fiyat',
    'Subscription.addProduct.AddProducts': 'Ürün ekle',
    'Subscription.addProduct.Confirm': 'Onayla',
    'Subscription.addProduct.Cancel': 'İptal',
    'Subscription.addProduct.search': 'Ara',
    'Subscription.index.EditPlan': 'Plan değiştir (Mama Dispenseri)',
    'Subscription.index.AddNewPlan': 'Yeni plan ekle (Mama Dispenseri)',
    'Subscription.index.OperateSuccessfully': 'Başarılı',
    'Subscription.index.UpdateFailed': 'Güncelleme başarısız',
    'Subscription.index.AddFailed': 'Ekleme başarısız',
    'Subscription.index.BasicInformation': 'Temel Bilgiler',
    'Subscription.index.TargetProduct': 'Hedef Ürün',
    'Subscription.index.EntryCriteria': 'Kriter girin',
    'Subscription.index.ExitRules': 'Çıkış Kuralları',
    'Subscription.index.Details': 'Detaylar',
    'Subscription.index.Return': 'Geri',
    'Subscription.index.NextStep': 'Sonraki Aşama',
    'Subscription.index.Save': 'Kaydet',
    'Subscription.index.Publish': 'Yayımla',
    'Subscription.quantityAndFrequency': 'Lütfen doğru adet ve frekansı girin!',
    'Subscription.AutNoStartoshipOrder.EnjoyDiscount': 'İndiriminizi güle güle kullanın!',
    'Subscription.Product': 'Ürün',
    'Subscription.DeliveryFrequency': 'Teslimat Frekansı',
    'Subscription.Subtotal': 'Ara Toplam',
    'Subscription.CustomHeader': 'Özel Başlık',
    'Subscription.SelectDate': 'Tarih seç',
    'Subscription.AreYouSure': 'Bu öğeyi atlamak istiyor musunuz?',
    'Subscription.SkipDelivery': 'Teslimatı atla',
    'Subscription.NoStart.Product': 'Ürün',
    'Subscription.NoStart.Quantity': 'Adet',
    'Subscription.NoStart.EnjoyDiscount': 'İndiriminizi güle güle kullanın!',
    'Subscription.NoStart.Amount': 'Miktar',
    'Subscription.NoStart.ShipmentDate': 'Sevkiyat Tarihi',
    'Subscription.NoStart.Operation': 'Operasyon',
    'Subscription.completed.Quantity': 'Adet',
    'Subscription.completed.EnjoyDiscount': 'İndiriminizi güle güle kullanın!',
    'Subscription.completed.Amount': 'Miktar',
    'Subscription.completed.ShipmentDate': 'Sevkiyat Tarihi',
    'Subscription.completed.OrderStatus': 'Sipariş Durumu',
    'Subscription.completed.Operation': 'Operasyon',
    'Subscription.Active.SubscriptionNumber': 'Abone Numarası',
    'Subscription.Active.SubscriptionDate': 'Abonelik Tarihi',
    'Subscription.Active.AuditorID': "Denetçi ID'si",
    'Subscription.Active.AuditorName': 'Denetçi Adı',
    'Subscription.Active.ConsumerName': 'Tüketici Adı',
    'Subscription.Active.ConsumerAccount': 'Tüketici Hesabı',
    'Subscription.Active.ConsumerType': 'Tüketici Tipi',
    'Subscription.Active.PhoneNumber': 'Telefon Numarası',
    'Subscription.Active.Subtotal': 'Ara Toplam',
    'Subscription.Active.Promotion': 'Promosyon',
    'Subscription.Active.Shipping': 'Sevkiyat',
    'Subscription.Active.Tax': 'Vergi',
    'Subscription.Active.Total': 'Toplam',
    'Subscription.Active.IVAInclude': 'IVA dahildir',
    'Subscription.Active.Change': 'Değiştir',
    'Subscription.Active.DeliveryAddress': 'Teslimat Adresi',
    'Subscription.Active.Name': 'Adı Soyadı',
    'Subscription.Active.CityCountry': 'Şehir, Ülke',
    'Subscription.Active.Address1': 'Adres 1 ',
    'Subscription.Active.Address2': 'Adres 2',
    'Subscription.Active.BillingAddress': 'Fatura Adresi',
    'Subscription.Active.BName': 'Adı Soyadı',
    'Subscription.Active.BCityCountry': 'Şehir, Ülke',
    'Subscription.Active.BAddress1': 'Adres 1 ',
    'Subscription.Active.BAddress2': 'Adres 2',
    'Subscription.Active.PaymentMethod': 'Ödeme Yöntemi',
    'Subscription.Active.PaymentMethod1': 'Ödeme Yöntemi',
    'Subscription.Active.CardNumber': 'Kart Numarası',
    'Subscription.Active.ChooseDeliveryAddress': 'Kaydedilmiş Teslimat Adresinden Seçin',
    'Subscription.Active.TheSameAs': 'Fatura adresi ile aynı',
    'Subscription.Active.UnfoldedAll': 'Tüm teslimat adresleri açıldı',
    'Subscription.Active.ChooseBillingAddress': 'Kaydedilen Fatura Adresinden Seçin',
    'Subscription.Active.UnfoldedAllDeliveryAddresses': 'Tüm teslimat adresleri açıldı',
    /* -------- 已翻译 V1.0---------------*/
};