/**
 * 多语言英文
 */
export default {
  'piece': '件',
  'total': '共',
  'product': 'productsss',
  'consumerList':'客户列表',
  'consumerName':'客户名称',
  'area'	:'所在地区',
  'selectAddress'	:'请选择地址',
  'platformLevel':'平台等级',
  'consumerType'	:'客户类型',
  'accountStatus'	:'账号状态',
  'accountNumber'	:'账号',
  'auditors'	:'业务员',
  'search' 	:'搜索',
    
  'all'	:'全部',
  'audited'	:'已审核',
  'pendingReview':	'待审核',
  'reviewFailed'	:'审核未通过',
  'contactPerson':	'联系人',
  'contactPhoneNumber'	:'联系方式',
  'approvalStatus'	:'审核状态',
  'tourist':	'游客',
  'platformConsumers':	'平台客户',
  'enable':	'启用',
  'disabled':'禁用',
  'consumerLevel':	'客户等级',
  'levelName'	:'等级名称',
  'levelBadge':	'等级徽章',
  'view':'查看',
  'operation':'操作',


  'orderDetails':	'订单详情',
  'deliveryRecord':	'发货记录',
  'collectionRecords':	'收款记录',
    
  'toBeDelivered'	:"待发货",
  'ship'	:"发货",
  'orderNumber':	"订单号",
  'consumer'	:"客户",
  'consumerAccount'	:"客户账号",
  'orderTime':	"下单时间",
    
  'skuCode':	"SKU编码",
  'productName':	"商品名称",
  'weight':	"规格",
  'price':	"单价",
  'quantity':	"数量",
  'subtotal':	"金额小计",
  'productAmount':	"商品金额",
  'pointsDeduction':	"积分抵扣",
  'shippingFees':	"配送费用",
  'totalPayable':	"应付总额",
    
  'sellerNotes':	"卖家备注",
  'buyerNotes':	"买家备注" ,

  'noData': '暂无数据',
  'save': '保存',

  


  'orderAttachment': "订单附件",
  'none': "无",
  'paymentMethod': "支付方式",
  'onlinePayment': "在线支付",
  'invoiceInformation': '发票信息',
  'generalInvoice': '普通发票 ',
  'details': '明细',
  'invoiceReceivingAddress': "发票收货地址",
  'deliveryMethod': '配送方式',
  'expressDelivery': "快递配送",
  'deliveryInformation':"收货信息",
  'confirm':'确认',
  'cancel':'取消',



  "serialNumber": "序号",
  "shipped": "已发货数",
  "thisShipment": "本次发货数",


  "amountReceivable": "应收金额",
  "collectionSerialNumber": "收款流水号",
  "collectionTime": "收款时间",
  "amountReceived": "实收金额",
  "accountsReceivable": "收款账户",
  "accessories": "附件",
  "status ": "状态",
  "paid": "已付款",
  "remarks": "备注",

  'productFirstLetterUpperCase': '商品',

  'recipient': '收件人',
  'recipientPhone': '收件人手机',


  'amount': '金额	',


  'order.orderList': '订单列表',
  'order.orderNumber': '订单编号',
  'order.shippingStatus': '发货状态',
  'order.paymentStatus': '付款状态',
  'order.orderStatus': '订单状态',
  'order.orderSource': '订单来源',
  'order.startDate': '开始日期',
  'order.endDate': '结束日期',
  'order.bulkOperations': '批量操作',
  'order.pendingReview': '待审核',
  'order.toBeFormed': '待成团',
  'order.notShipped': '未发货',
  'order.toBeDelivered': '待发货',
  'order.toBeReceived': '待收货',
  'order.paid': '已付款',
  'order.unpaid': '未付款',
  'order.toBeConfirmed': '待确认',
  'order.received': '已收货',
  'order.confirmReceipt': '确认收货',
  'order.completed': '已完成',
  'order.outOfDate': '已作废',
  'order.ship': '发货',
  'order.allShipments': '全部发货',
  'order.partialShipment': '部分发货',
  'order.invalid': '作废',
  'order.unknown': '未知',
  'order.seeDetails': '查看详情',
  'order.PCOrder': 'PC订单',
  'order.H5Order': 'H5订单',
  'order.AppOrder': 'APP订单',
  'order.miniProgramOrder': '小程序订单',
  'order.rejectionReasonTip': '请输入驳回原因',
  'order.100charactersLimitTip': '备注请填写小于100字符',
  'order.valetOrder': '代客下单',
  'order.fightTogether': '拼团',
  'order.audit': '审核',
  'order.turnDown': '驳回',
  'order.review': '回审',
  'order.confirmReceivedAllProducts': '确认已收到全部货品?',
  'order.confirmReview': '确认将选中的订单退回重新审核?',
  'order.confirmAudit': '确认审核已选择订单?',
  'order.exportFilterOrder': '导出筛选出的订单',
  'order.exportSelectedOrder': '导出选中的订单',
  'order.pleaseSelectOrderToOperate': '请选择需要操作的订单',
  'order.batchReview': '批量审核',
  'order.batchExpert': '批量导出',




  'operationLog':'操作日志',
  'operatorType':'操作方',
  'operator':'操作人',
  'time':'时间',
  'operationCategory':'操作类别',
  'paymentOrder':'订单支付',
  'createOrder':'创建订单',
  'order':'订单',
  'back':'返回',

  "initiateApplication":"发起售后申请",
  "amountQuantity"	:	"金额数量",
  "shippingStatus"	:	"发货状态",
"orderStatus"	:	"订单状态",
"paymentStatus"	:	"付款状态",
"notShipped"	:	"未发货",
"application"	:	"申请",
"newChargeback"	:	"新增退单",
"refundInformation"	:	"退单信息",
"refundReason": "退单原因"	,
"selectRefundReacon": "请选择退单原因",
"returnInstructions":"退货说明",
"attachmentInformation":"附件信息",

"attachmentTips":"请将您的退货凭据添加到附件,支持的图片格式：jpg、jpeg、png、gif，文件大小不超过5M,最多上传10张",
"refundableAmount":"应退金额",
"pointsRefundable":"应退积分",
"commodity":'商品'

};